/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_m_2.hxx"
#include "includes/cuda_lib_nn_m_2.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	int32_t ii_T3ZVcfaxJo_bzn5JEqJlF;
	float* lon_Io6aUiQoej;
	float* neighbor_dist_7ePsJk8LgK;
	int64_t* times_In9RANrjEd;
	int32_t* neighbor_id_3k5gEMr1AZ;
	float target_lat_3AtWsMhDEH;
	float target_lon_tyeR8pi8x5;
	float* lat_sMjqJMrZb7;
	float* dists_WHNOXlPeSR;
	int NUM_CORES;
	int NUM_GPUS;

	int rank, nprocs;
	MPI_Status Stat;
	MPI_Init(&argc, &argv);
	MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
	if (rank == 0 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	} else 	if (rank == 1 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	}
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_7ePsJk8LgK = Init_List(100000, neighbor_dist_7ePsJk8LgK, 5LL * 1LL);
	dists_WHNOXlPeSR = Init_List(dists_WHNOXlPeSR, 42764LL * 1LL);
	lon_Io6aUiQoej = Init_List(lon_Io6aUiQoej, 42764LL * 1LL);
	neighbor_id_3k5gEMr1AZ = Init_List(neighbor_id_3k5gEMr1AZ, 5LL * 1LL);
	times_In9RANrjEd = Init_List(times_In9RANrjEd, 4LL * 1LL);
	lat_sMjqJMrZb7 = Init_List(lat_sMjqJMrZb7, 42764LL * 1LL);
	if (rank == 0) {
		ii_T3ZVcfaxJo_bzn5JEqJlF = 0;
	}
	if (rank == 0) {
		target_lon_tyeR8pi8x5 = 90;
		target_lat_3AtWsMhDEH = 30;
	}
	if (rank == 0) {
		
if ((ii_T3ZVcfaxJo_bzn5JEqJlF == 0)) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 1) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 2) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[0] = get_time();
auto f_1_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 0; INDEX_XUo9HH9Vcz < 0 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(0)->addWork(f_1_XUo9HH9Vcz);
		auto f_2_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 1859; INDEX_XUo9HH9Vcz < 1859 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(1)->addWork(f_2_XUo9HH9Vcz);
		auto f_3_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 3718; INDEX_XUo9HH9Vcz < 3718 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(2)->addWork(f_3_XUo9HH9Vcz);
		auto f_4_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 5577; INDEX_XUo9HH9Vcz < 5577 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(3)->addWork(f_4_XUo9HH9Vcz);
		auto f_5_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 7436; INDEX_XUo9HH9Vcz < 7436 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(4)->addWork(f_5_XUo9HH9Vcz);
		auto f_6_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 9295; INDEX_XUo9HH9Vcz < 9295 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(5)->addWork(f_6_XUo9HH9Vcz);
		auto f_7_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 11154; INDEX_XUo9HH9Vcz < 11154 + 1859; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(6)->addWork(f_7_XUo9HH9Vcz);
		auto f_8_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 13013; INDEX_XUo9HH9Vcz < 13013 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(7)->addWork(f_8_XUo9HH9Vcz);
		auto f_9_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 14871; INDEX_XUo9HH9Vcz < 14871 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(8)->addWork(f_9_XUo9HH9Vcz);
		auto f_10_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 16729; INDEX_XUo9HH9Vcz < 16729 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(9)->addWork(f_10_XUo9HH9Vcz);
		auto f_11_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 18587; INDEX_XUo9HH9Vcz < 18587 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(10)->addWork(f_11_XUo9HH9Vcz);
		auto f_12_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 20445; INDEX_XUo9HH9Vcz < 20445 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(11)->addWork(f_12_XUo9HH9Vcz);
		auto f_13_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 22303; INDEX_XUo9HH9Vcz < 22303 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(12)->addWork(f_13_XUo9HH9Vcz);
		auto f_14_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 24161; INDEX_XUo9HH9Vcz < 24161 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(13)->addWork(f_14_XUo9HH9Vcz);
		auto f_15_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 26019; INDEX_XUo9HH9Vcz < 26019 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(14)->addWork(f_15_XUo9HH9Vcz);
		auto f_16_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 27877; INDEX_XUo9HH9Vcz < 27877 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(15)->addWork(f_16_XUo9HH9Vcz);
		auto f_17_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 29735; INDEX_XUo9HH9Vcz < 29735 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(16)->addWork(f_17_XUo9HH9Vcz);
		auto f_18_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 31593; INDEX_XUo9HH9Vcz < 31593 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(17)->addWork(f_18_XUo9HH9Vcz);
		auto f_19_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 33451; INDEX_XUo9HH9Vcz < 33451 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(18)->addWork(f_19_XUo9HH9Vcz);
		auto f_20_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 35309; INDEX_XUo9HH9Vcz < 35309 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(19)->addWork(f_20_XUo9HH9Vcz);
		auto f_21_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 37167; INDEX_XUo9HH9Vcz < 37167 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(20)->addWork(f_21_XUo9HH9Vcz);
		auto f_22_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 39025; INDEX_XUo9HH9Vcz < 39025 + 1858; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(21)->addWork(f_22_XUo9HH9Vcz);
		auto f_23_XUo9HH9Vcz = [&] () {
			for (size_t INDEX_XUo9HH9Vcz = 40883; INDEX_XUo9HH9Vcz < 40883 + 1881; ++INDEX_XUo9HH9Vcz) {
				dists_WHNOXlPeSR[(INDEX_XUo9HH9Vcz)] = sqrt((lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_XUo9HH9Vcz)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_XUo9HH9Vcz)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(22)->addWork(f_23_XUo9HH9Vcz);
	}
	if (rank == 0) {
		ii_T3ZVcfaxJo_bzn5JEqJlF++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_LHiX4kjojN = new Bit_Mask(47,true);
		for (size_t i_6rFzcnvHQg = 0; i_6rFzcnvHQg < 23; ++i_6rFzcnvHQg) {
			mask_ptr_LHiX4kjojN->setBarrier(i_6rFzcnvHQg);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_LHiX4kjojN (mask_ptr_LHiX4kjojN);
		self_barrier(boost_mask_ptr_LHiX4kjojN);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_7ePsJk8LgK[(j)] > max_val) {
					max_val = neighbor_dist_7ePsJk8LgK[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_WHNOXlPeSR[(i)]) {
				neighbor_dist_7ePsJk8LgK[(max_id)] = dists_WHNOXlPeSR[(i)];
				neighbor_id_3k5gEMr1AZ[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[0] = get_time() - time[0];
if ((ii_T3ZVcfaxJo_bzn5JEqJlF == 0)) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 1) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 2) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[1] = get_time();
auto f_1_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 0; INDEX_76uL4WC4rh < 0 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(0)->addWork(f_1_76uL4WC4rh);
		auto f_2_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 1859; INDEX_76uL4WC4rh < 1859 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(1)->addWork(f_2_76uL4WC4rh);
		auto f_3_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 3718; INDEX_76uL4WC4rh < 3718 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(2)->addWork(f_3_76uL4WC4rh);
		auto f_4_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 5577; INDEX_76uL4WC4rh < 5577 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(3)->addWork(f_4_76uL4WC4rh);
		auto f_5_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 7436; INDEX_76uL4WC4rh < 7436 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(4)->addWork(f_5_76uL4WC4rh);
		auto f_6_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 9295; INDEX_76uL4WC4rh < 9295 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(5)->addWork(f_6_76uL4WC4rh);
		auto f_7_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 11154; INDEX_76uL4WC4rh < 11154 + 1859; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(6)->addWork(f_7_76uL4WC4rh);
		auto f_8_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 13013; INDEX_76uL4WC4rh < 13013 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(7)->addWork(f_8_76uL4WC4rh);
		auto f_9_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 14871; INDEX_76uL4WC4rh < 14871 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(8)->addWork(f_9_76uL4WC4rh);
		auto f_10_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 16729; INDEX_76uL4WC4rh < 16729 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(9)->addWork(f_10_76uL4WC4rh);
		auto f_11_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 18587; INDEX_76uL4WC4rh < 18587 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(10)->addWork(f_11_76uL4WC4rh);
		auto f_12_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 20445; INDEX_76uL4WC4rh < 20445 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(11)->addWork(f_12_76uL4WC4rh);
		auto f_13_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 22303; INDEX_76uL4WC4rh < 22303 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(12)->addWork(f_13_76uL4WC4rh);
		auto f_14_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 24161; INDEX_76uL4WC4rh < 24161 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(13)->addWork(f_14_76uL4WC4rh);
		auto f_15_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 26019; INDEX_76uL4WC4rh < 26019 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(14)->addWork(f_15_76uL4WC4rh);
		auto f_16_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 27877; INDEX_76uL4WC4rh < 27877 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(15)->addWork(f_16_76uL4WC4rh);
		auto f_17_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 29735; INDEX_76uL4WC4rh < 29735 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(16)->addWork(f_17_76uL4WC4rh);
		auto f_18_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 31593; INDEX_76uL4WC4rh < 31593 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(17)->addWork(f_18_76uL4WC4rh);
		auto f_19_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 33451; INDEX_76uL4WC4rh < 33451 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(18)->addWork(f_19_76uL4WC4rh);
		auto f_20_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 35309; INDEX_76uL4WC4rh < 35309 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(19)->addWork(f_20_76uL4WC4rh);
		auto f_21_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 37167; INDEX_76uL4WC4rh < 37167 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(20)->addWork(f_21_76uL4WC4rh);
		auto f_22_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 39025; INDEX_76uL4WC4rh < 39025 + 1858; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(21)->addWork(f_22_76uL4WC4rh);
		auto f_23_76uL4WC4rh = [&] () {
			for (size_t INDEX_76uL4WC4rh = 40883; INDEX_76uL4WC4rh < 40883 + 1881; ++INDEX_76uL4WC4rh) {
				dists_WHNOXlPeSR[(INDEX_76uL4WC4rh)] = sqrt((lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_76uL4WC4rh)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_76uL4WC4rh)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(22)->addWork(f_23_76uL4WC4rh);
	}
	if (rank == 0) {
		ii_T3ZVcfaxJo_bzn5JEqJlF++;
	}
	if (rank == 0) {
		time[1] = get_time() - time[1];
if ((ii_T3ZVcfaxJo_bzn5JEqJlF == 0)) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 1) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 2) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_LWvOhJBrYq = new Bit_Mask(47,true);
		for (size_t i_pBJ7vcQ1ij = 0; i_pBJ7vcQ1ij < 23; ++i_pBJ7vcQ1ij) {
			mask_ptr_LWvOhJBrYq->setBarrier(i_pBJ7vcQ1ij);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_LWvOhJBrYq (mask_ptr_LWvOhJBrYq);
		self_barrier(boost_mask_ptr_LWvOhJBrYq);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_7ePsJk8LgK[(j)] > max_val) {
					max_val = neighbor_dist_7ePsJk8LgK[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_WHNOXlPeSR[(i)]) {
				neighbor_dist_7ePsJk8LgK[(max_id)] = dists_WHNOXlPeSR[(i)];
				neighbor_id_3k5gEMr1AZ[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time();
auto f_1_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 0; INDEX_bYZ9HqKnLy < 0 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(0)->addWork(f_1_bYZ9HqKnLy);
		auto f_2_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 1859; INDEX_bYZ9HqKnLy < 1859 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(1)->addWork(f_2_bYZ9HqKnLy);
		auto f_3_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 3718; INDEX_bYZ9HqKnLy < 3718 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(2)->addWork(f_3_bYZ9HqKnLy);
		auto f_4_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 5577; INDEX_bYZ9HqKnLy < 5577 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(3)->addWork(f_4_bYZ9HqKnLy);
		auto f_5_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 7436; INDEX_bYZ9HqKnLy < 7436 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(4)->addWork(f_5_bYZ9HqKnLy);
		auto f_6_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 9295; INDEX_bYZ9HqKnLy < 9295 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(5)->addWork(f_6_bYZ9HqKnLy);
		auto f_7_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 11154; INDEX_bYZ9HqKnLy < 11154 + 1859; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(6)->addWork(f_7_bYZ9HqKnLy);
		auto f_8_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 13013; INDEX_bYZ9HqKnLy < 13013 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(7)->addWork(f_8_bYZ9HqKnLy);
		auto f_9_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 14871; INDEX_bYZ9HqKnLy < 14871 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(8)->addWork(f_9_bYZ9HqKnLy);
		auto f_10_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 16729; INDEX_bYZ9HqKnLy < 16729 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(9)->addWork(f_10_bYZ9HqKnLy);
		auto f_11_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 18587; INDEX_bYZ9HqKnLy < 18587 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(10)->addWork(f_11_bYZ9HqKnLy);
		auto f_12_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 20445; INDEX_bYZ9HqKnLy < 20445 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(11)->addWork(f_12_bYZ9HqKnLy);
		auto f_13_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 22303; INDEX_bYZ9HqKnLy < 22303 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(12)->addWork(f_13_bYZ9HqKnLy);
		auto f_14_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 24161; INDEX_bYZ9HqKnLy < 24161 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(13)->addWork(f_14_bYZ9HqKnLy);
		auto f_15_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 26019; INDEX_bYZ9HqKnLy < 26019 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(14)->addWork(f_15_bYZ9HqKnLy);
		auto f_16_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 27877; INDEX_bYZ9HqKnLy < 27877 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(15)->addWork(f_16_bYZ9HqKnLy);
		auto f_17_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 29735; INDEX_bYZ9HqKnLy < 29735 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(16)->addWork(f_17_bYZ9HqKnLy);
		auto f_18_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 31593; INDEX_bYZ9HqKnLy < 31593 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(17)->addWork(f_18_bYZ9HqKnLy);
		auto f_19_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 33451; INDEX_bYZ9HqKnLy < 33451 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(18)->addWork(f_19_bYZ9HqKnLy);
		auto f_20_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 35309; INDEX_bYZ9HqKnLy < 35309 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(19)->addWork(f_20_bYZ9HqKnLy);
		auto f_21_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 37167; INDEX_bYZ9HqKnLy < 37167 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(20)->addWork(f_21_bYZ9HqKnLy);
		auto f_22_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 39025; INDEX_bYZ9HqKnLy < 39025 + 1858; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(21)->addWork(f_22_bYZ9HqKnLy);
		auto f_23_bYZ9HqKnLy = [&] () {
			for (size_t INDEX_bYZ9HqKnLy = 40883; INDEX_bYZ9HqKnLy < 40883 + 1881; ++INDEX_bYZ9HqKnLy) {
				dists_WHNOXlPeSR[(INDEX_bYZ9HqKnLy)] = sqrt((lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_bYZ9HqKnLy)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_bYZ9HqKnLy)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(22)->addWork(f_23_bYZ9HqKnLy);
	}
	if (rank == 0) {
		ii_T3ZVcfaxJo_bzn5JEqJlF++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_t5AcieFHPt = new Bit_Mask(47,true);
		for (size_t i_JGbmTyWSVd = 0; i_JGbmTyWSVd < 23; ++i_JGbmTyWSVd) {
			mask_ptr_t5AcieFHPt->setBarrier(i_JGbmTyWSVd);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_t5AcieFHPt (mask_ptr_t5AcieFHPt);
		self_barrier(boost_mask_ptr_t5AcieFHPt);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_7ePsJk8LgK[(j)] > max_val) {
					max_val = neighbor_dist_7ePsJk8LgK[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_WHNOXlPeSR[(i)]) {
				neighbor_dist_7ePsJk8LgK[(max_id)] = dists_WHNOXlPeSR[(i)];
				neighbor_id_3k5gEMr1AZ[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time() - time[2];
if ((ii_T3ZVcfaxJo_bzn5JEqJlF == 0)) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 1) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_T3ZVcfaxJo_bzn5JEqJlF == 2) {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_Io6aUiQoej, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_sMjqJMrZb7, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[3] = get_time();
auto f_1_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 0; INDEX_VKjQPvc5nO < 0 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(0)->addWork(f_1_VKjQPvc5nO);
		auto f_2_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 1859; INDEX_VKjQPvc5nO < 1859 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(1)->addWork(f_2_VKjQPvc5nO);
		auto f_3_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 3718; INDEX_VKjQPvc5nO < 3718 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(2)->addWork(f_3_VKjQPvc5nO);
		auto f_4_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 5577; INDEX_VKjQPvc5nO < 5577 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(3)->addWork(f_4_VKjQPvc5nO);
		auto f_5_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 7436; INDEX_VKjQPvc5nO < 7436 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(4)->addWork(f_5_VKjQPvc5nO);
		auto f_6_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 9295; INDEX_VKjQPvc5nO < 9295 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(5)->addWork(f_6_VKjQPvc5nO);
		auto f_7_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 11154; INDEX_VKjQPvc5nO < 11154 + 1859; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(6)->addWork(f_7_VKjQPvc5nO);
		auto f_8_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 13013; INDEX_VKjQPvc5nO < 13013 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(7)->addWork(f_8_VKjQPvc5nO);
		auto f_9_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 14871; INDEX_VKjQPvc5nO < 14871 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(8)->addWork(f_9_VKjQPvc5nO);
		auto f_10_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 16729; INDEX_VKjQPvc5nO < 16729 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(9)->addWork(f_10_VKjQPvc5nO);
		auto f_11_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 18587; INDEX_VKjQPvc5nO < 18587 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(10)->addWork(f_11_VKjQPvc5nO);
		auto f_12_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 20445; INDEX_VKjQPvc5nO < 20445 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(11)->addWork(f_12_VKjQPvc5nO);
		auto f_13_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 22303; INDEX_VKjQPvc5nO < 22303 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(12)->addWork(f_13_VKjQPvc5nO);
		auto f_14_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 24161; INDEX_VKjQPvc5nO < 24161 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(13)->addWork(f_14_VKjQPvc5nO);
		auto f_15_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 26019; INDEX_VKjQPvc5nO < 26019 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(14)->addWork(f_15_VKjQPvc5nO);
		auto f_16_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 27877; INDEX_VKjQPvc5nO < 27877 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(15)->addWork(f_16_VKjQPvc5nO);
		auto f_17_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 29735; INDEX_VKjQPvc5nO < 29735 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(16)->addWork(f_17_VKjQPvc5nO);
		auto f_18_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 31593; INDEX_VKjQPvc5nO < 31593 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(17)->addWork(f_18_VKjQPvc5nO);
		auto f_19_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 33451; INDEX_VKjQPvc5nO < 33451 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(18)->addWork(f_19_VKjQPvc5nO);
		auto f_20_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 35309; INDEX_VKjQPvc5nO < 35309 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(19)->addWork(f_20_VKjQPvc5nO);
		auto f_21_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 37167; INDEX_VKjQPvc5nO < 37167 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(20)->addWork(f_21_VKjQPvc5nO);
		auto f_22_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 39025; INDEX_VKjQPvc5nO < 39025 + 1858; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(21)->addWork(f_22_VKjQPvc5nO);
		auto f_23_VKjQPvc5nO = [&] () {
			for (size_t INDEX_VKjQPvc5nO = 40883; INDEX_VKjQPvc5nO < 40883 + 1881; ++INDEX_VKjQPvc5nO) {
				dists_WHNOXlPeSR[(INDEX_VKjQPvc5nO)] = sqrt((lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) * (lon_Io6aUiQoej[(INDEX_VKjQPvc5nO)] - target_lon_tyeR8pi8x5) + (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH) * (lat_sMjqJMrZb7[(INDEX_VKjQPvc5nO)] - target_lat_3AtWsMhDEH));
			}
		};
		getPool()->at(22)->addWork(f_23_VKjQPvc5nO);
	}
	if (rank == 0) {
		ii_T3ZVcfaxJo_bzn5JEqJlF++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_sKckNzLJoA = new Bit_Mask(47,true);
		for (size_t i_Y0qhD6DL2O = 0; i_Y0qhD6DL2O < 23; ++i_Y0qhD6DL2O) {
			mask_ptr_sKckNzLJoA->setBarrier(i_Y0qhD6DL2O);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_sKckNzLJoA (mask_ptr_sKckNzLJoA);
		self_barrier(boost_mask_ptr_sKckNzLJoA);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_7ePsJk8LgK[(j)] > max_val) {
					max_val = neighbor_dist_7ePsJk8LgK[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_WHNOXlPeSR[(i)]) {
				neighbor_dist_7ePsJk8LgK[(max_id)] = dists_WHNOXlPeSR[(i)];
				neighbor_id_3k5gEMr1AZ[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_7ePsJk8LgK, 1LL * 5);
		array_write("canes.txt", neighbor_id_3k5gEMr1AZ, 1LL * 5);
	}
	finishExecution();
	finishGPUExecution();
	std::free(lon_Io6aUiQoej);
	std::free(neighbor_dist_7ePsJk8LgK);
	std::free(times_In9RANrjEd);
	std::free(neighbor_id_3k5gEMr1AZ);
	std::free(lat_sMjqJMrZb7);
	std::free(dists_WHNOXlPeSR);
	MPI_Finalize();
	return 0;


}

