<#assign gh = glex.getGlobalVar("pfHelper")> <#-- GeneratorHelper -->
${signature("module")}
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef ${gh.getFilename()}_HXX
#define ${gh.getFilename()}_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

<#assign functions=gh.getSerialFunctions()>
<#list functions as func>
    ${gh.printFunctionType(func)} ${func.getIdentifier()}${gh.printArguments(func)};
</#list>

<#assign functions=gh.getRecursiveFunctions()>
<#list functions as func>
    ${gh.printFunctionType(func)} ${func.getIdentifier()}${gh.printArguments(func)};
</#list>

#endif