/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

<#assign gh=glex.getGlobalVar("pfHelper")> <#-- GeneratorHelper -->
#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/${gh.getFilename()}.hxx"
#include "includes/cuda_lib_${gh.getFilename()}.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/

${gh.printGlobalVars(false)}

/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {

${gh.printRoot()}

}

