/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_g_1.hxx"
#include "includes/cuda_lib_nn_g_1.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	float* lon_GUQVOlW7KC;
	int32_t ii_tSOGPfMTth_uSZXO80NHP;
	float* neighbor_dist_HfIAUAz4PZ;
	int64_t* times_YDfvo4KzDv;
	int32_t* neighbor_id_QDQN1MrBKf;
	float target_lat_kx4lgNzClJ;
	float target_lon_APY3Ai6raf;
	float* lat_tJnUPyK0mL;
	float* dists_DrLizMW2Tx;
	int NUM_CORES;
	int NUM_GPUS;

	NUM_CORES = 47;
	NUM_GPUS = 0;
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_HfIAUAz4PZ = Init_List(100000, neighbor_dist_HfIAUAz4PZ, 5LL * 1LL);
	dists_DrLizMW2Tx = Init_List(dists_DrLizMW2Tx, 42764LL * 1LL);
	lon_GUQVOlW7KC = Init_List(lon_GUQVOlW7KC, 42764LL * 1LL);
	neighbor_id_QDQN1MrBKf = Init_List(neighbor_id_QDQN1MrBKf, 5LL * 1LL);
	times_YDfvo4KzDv = Init_List(times_YDfvo4KzDv, 4LL * 1LL);
	lat_tJnUPyK0mL = Init_List(lat_tJnUPyK0mL, 42764LL * 1LL);
	ii_tSOGPfMTth_uSZXO80NHP = 0;
	target_lon_APY3Ai6raf = 90;
	target_lat_kx4lgNzClJ = 30;
	
if ((ii_tSOGPfMTth_uSZXO80NHP == 0)) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 1) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 2) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[0] = get_time();
auto f_1_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 0; INDEX_yAG9XAB2vk < 0 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(0)->addWork(f_1_yAG9XAB2vk);
	auto f_2_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 1859; INDEX_yAG9XAB2vk < 1859 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(1)->addWork(f_2_yAG9XAB2vk);
	auto f_3_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 3718; INDEX_yAG9XAB2vk < 3718 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(2)->addWork(f_3_yAG9XAB2vk);
	auto f_4_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 5577; INDEX_yAG9XAB2vk < 5577 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(3)->addWork(f_4_yAG9XAB2vk);
	auto f_5_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 7436; INDEX_yAG9XAB2vk < 7436 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(4)->addWork(f_5_yAG9XAB2vk);
	auto f_6_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 9295; INDEX_yAG9XAB2vk < 9295 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(5)->addWork(f_6_yAG9XAB2vk);
	auto f_7_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 11154; INDEX_yAG9XAB2vk < 11154 + 1859; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(6)->addWork(f_7_yAG9XAB2vk);
	auto f_8_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 13013; INDEX_yAG9XAB2vk < 13013 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(7)->addWork(f_8_yAG9XAB2vk);
	auto f_9_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 14871; INDEX_yAG9XAB2vk < 14871 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(8)->addWork(f_9_yAG9XAB2vk);
	auto f_10_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 16729; INDEX_yAG9XAB2vk < 16729 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(9)->addWork(f_10_yAG9XAB2vk);
	auto f_11_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 18587; INDEX_yAG9XAB2vk < 18587 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(10)->addWork(f_11_yAG9XAB2vk);
	auto f_12_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 20445; INDEX_yAG9XAB2vk < 20445 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(11)->addWork(f_12_yAG9XAB2vk);
	auto f_13_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 22303; INDEX_yAG9XAB2vk < 22303 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(12)->addWork(f_13_yAG9XAB2vk);
	auto f_14_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 24161; INDEX_yAG9XAB2vk < 24161 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(13)->addWork(f_14_yAG9XAB2vk);
	auto f_15_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 26019; INDEX_yAG9XAB2vk < 26019 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(14)->addWork(f_15_yAG9XAB2vk);
	auto f_16_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 27877; INDEX_yAG9XAB2vk < 27877 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(15)->addWork(f_16_yAG9XAB2vk);
	auto f_17_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 29735; INDEX_yAG9XAB2vk < 29735 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(16)->addWork(f_17_yAG9XAB2vk);
	auto f_18_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 31593; INDEX_yAG9XAB2vk < 31593 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(17)->addWork(f_18_yAG9XAB2vk);
	auto f_19_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 33451; INDEX_yAG9XAB2vk < 33451 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(18)->addWork(f_19_yAG9XAB2vk);
	auto f_20_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 35309; INDEX_yAG9XAB2vk < 35309 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(19)->addWork(f_20_yAG9XAB2vk);
	auto f_21_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 37167; INDEX_yAG9XAB2vk < 37167 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(20)->addWork(f_21_yAG9XAB2vk);
	auto f_22_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 39025; INDEX_yAG9XAB2vk < 39025 + 1858; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(21)->addWork(f_22_yAG9XAB2vk);
	auto f_23_yAG9XAB2vk = [&] () {
		for (size_t INDEX_yAG9XAB2vk = 40883; INDEX_yAG9XAB2vk < 40883 + 1881; ++INDEX_yAG9XAB2vk) {
			dists_DrLizMW2Tx[(INDEX_yAG9XAB2vk)] = sqrt((lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_yAG9XAB2vk)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_yAG9XAB2vk)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(22)->addWork(f_23_yAG9XAB2vk);
	ii_tSOGPfMTth_uSZXO80NHP++;
	Bit_Mask * mask_ptr_FzkR3b7isK = new Bit_Mask(47,true);
	for (size_t i_C4kZza1yHM = 0; i_C4kZza1yHM < 23; ++i_C4kZza1yHM) {
		mask_ptr_FzkR3b7isK->setBarrier(i_C4kZza1yHM);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_FzkR3b7isK (mask_ptr_FzkR3b7isK);
	self_barrier(boost_mask_ptr_FzkR3b7isK);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_HfIAUAz4PZ[(j)] > max_val) {
				max_val = neighbor_dist_HfIAUAz4PZ[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_DrLizMW2Tx[(i)]) {
			neighbor_dist_HfIAUAz4PZ[(max_id)] = dists_DrLizMW2Tx[(i)];
			neighbor_id_QDQN1MrBKf[(max_id)] = i;
		}
	}
	time[0] = get_time() - time[0];
if ((ii_tSOGPfMTth_uSZXO80NHP == 0)) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 1) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 2) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[1] = get_time();
auto f_1_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 0; INDEX_2ujgQ0qh7r < 0 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(0)->addWork(f_1_2ujgQ0qh7r);
	auto f_2_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 1859; INDEX_2ujgQ0qh7r < 1859 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(1)->addWork(f_2_2ujgQ0qh7r);
	auto f_3_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 3718; INDEX_2ujgQ0qh7r < 3718 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(2)->addWork(f_3_2ujgQ0qh7r);
	auto f_4_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 5577; INDEX_2ujgQ0qh7r < 5577 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(3)->addWork(f_4_2ujgQ0qh7r);
	auto f_5_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 7436; INDEX_2ujgQ0qh7r < 7436 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(4)->addWork(f_5_2ujgQ0qh7r);
	auto f_6_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 9295; INDEX_2ujgQ0qh7r < 9295 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(5)->addWork(f_6_2ujgQ0qh7r);
	auto f_7_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 11154; INDEX_2ujgQ0qh7r < 11154 + 1859; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(6)->addWork(f_7_2ujgQ0qh7r);
	auto f_8_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 13013; INDEX_2ujgQ0qh7r < 13013 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(7)->addWork(f_8_2ujgQ0qh7r);
	auto f_9_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 14871; INDEX_2ujgQ0qh7r < 14871 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(8)->addWork(f_9_2ujgQ0qh7r);
	auto f_10_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 16729; INDEX_2ujgQ0qh7r < 16729 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(9)->addWork(f_10_2ujgQ0qh7r);
	auto f_11_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 18587; INDEX_2ujgQ0qh7r < 18587 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(10)->addWork(f_11_2ujgQ0qh7r);
	auto f_12_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 20445; INDEX_2ujgQ0qh7r < 20445 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(11)->addWork(f_12_2ujgQ0qh7r);
	auto f_13_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 22303; INDEX_2ujgQ0qh7r < 22303 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(12)->addWork(f_13_2ujgQ0qh7r);
	auto f_14_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 24161; INDEX_2ujgQ0qh7r < 24161 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(13)->addWork(f_14_2ujgQ0qh7r);
	auto f_15_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 26019; INDEX_2ujgQ0qh7r < 26019 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(14)->addWork(f_15_2ujgQ0qh7r);
	auto f_16_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 27877; INDEX_2ujgQ0qh7r < 27877 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(15)->addWork(f_16_2ujgQ0qh7r);
	auto f_17_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 29735; INDEX_2ujgQ0qh7r < 29735 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(16)->addWork(f_17_2ujgQ0qh7r);
	auto f_18_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 31593; INDEX_2ujgQ0qh7r < 31593 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(17)->addWork(f_18_2ujgQ0qh7r);
	auto f_19_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 33451; INDEX_2ujgQ0qh7r < 33451 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(18)->addWork(f_19_2ujgQ0qh7r);
	auto f_20_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 35309; INDEX_2ujgQ0qh7r < 35309 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(19)->addWork(f_20_2ujgQ0qh7r);
	auto f_21_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 37167; INDEX_2ujgQ0qh7r < 37167 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(20)->addWork(f_21_2ujgQ0qh7r);
	auto f_22_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 39025; INDEX_2ujgQ0qh7r < 39025 + 1858; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(21)->addWork(f_22_2ujgQ0qh7r);
	auto f_23_2ujgQ0qh7r = [&] () {
		for (size_t INDEX_2ujgQ0qh7r = 40883; INDEX_2ujgQ0qh7r < 40883 + 1881; ++INDEX_2ujgQ0qh7r) {
			dists_DrLizMW2Tx[(INDEX_2ujgQ0qh7r)] = sqrt((lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_2ujgQ0qh7r)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_2ujgQ0qh7r)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(22)->addWork(f_23_2ujgQ0qh7r);
	ii_tSOGPfMTth_uSZXO80NHP++;
	time[1] = get_time() - time[1];
if ((ii_tSOGPfMTth_uSZXO80NHP == 0)) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 1) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 2) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	Bit_Mask * mask_ptr_96I0bK57HP = new Bit_Mask(47,true);
	for (size_t i_iQZMqvRzdG = 0; i_iQZMqvRzdG < 23; ++i_iQZMqvRzdG) {
		mask_ptr_96I0bK57HP->setBarrier(i_iQZMqvRzdG);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_96I0bK57HP (mask_ptr_96I0bK57HP);
	self_barrier(boost_mask_ptr_96I0bK57HP);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_HfIAUAz4PZ[(j)] > max_val) {
				max_val = neighbor_dist_HfIAUAz4PZ[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_DrLizMW2Tx[(i)]) {
			neighbor_dist_HfIAUAz4PZ[(max_id)] = dists_DrLizMW2Tx[(i)];
			neighbor_id_QDQN1MrBKf[(max_id)] = i;
		}
	}
	time[2] = get_time();
auto f_1_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 0; INDEX_de8cslTo47 < 0 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(0)->addWork(f_1_de8cslTo47);
	auto f_2_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 1859; INDEX_de8cslTo47 < 1859 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(1)->addWork(f_2_de8cslTo47);
	auto f_3_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 3718; INDEX_de8cslTo47 < 3718 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(2)->addWork(f_3_de8cslTo47);
	auto f_4_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 5577; INDEX_de8cslTo47 < 5577 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(3)->addWork(f_4_de8cslTo47);
	auto f_5_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 7436; INDEX_de8cslTo47 < 7436 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(4)->addWork(f_5_de8cslTo47);
	auto f_6_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 9295; INDEX_de8cslTo47 < 9295 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(5)->addWork(f_6_de8cslTo47);
	auto f_7_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 11154; INDEX_de8cslTo47 < 11154 + 1859; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(6)->addWork(f_7_de8cslTo47);
	auto f_8_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 13013; INDEX_de8cslTo47 < 13013 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(7)->addWork(f_8_de8cslTo47);
	auto f_9_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 14871; INDEX_de8cslTo47 < 14871 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(8)->addWork(f_9_de8cslTo47);
	auto f_10_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 16729; INDEX_de8cslTo47 < 16729 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(9)->addWork(f_10_de8cslTo47);
	auto f_11_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 18587; INDEX_de8cslTo47 < 18587 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(10)->addWork(f_11_de8cslTo47);
	auto f_12_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 20445; INDEX_de8cslTo47 < 20445 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(11)->addWork(f_12_de8cslTo47);
	auto f_13_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 22303; INDEX_de8cslTo47 < 22303 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(12)->addWork(f_13_de8cslTo47);
	auto f_14_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 24161; INDEX_de8cslTo47 < 24161 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(13)->addWork(f_14_de8cslTo47);
	auto f_15_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 26019; INDEX_de8cslTo47 < 26019 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(14)->addWork(f_15_de8cslTo47);
	auto f_16_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 27877; INDEX_de8cslTo47 < 27877 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(15)->addWork(f_16_de8cslTo47);
	auto f_17_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 29735; INDEX_de8cslTo47 < 29735 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(16)->addWork(f_17_de8cslTo47);
	auto f_18_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 31593; INDEX_de8cslTo47 < 31593 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(17)->addWork(f_18_de8cslTo47);
	auto f_19_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 33451; INDEX_de8cslTo47 < 33451 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(18)->addWork(f_19_de8cslTo47);
	auto f_20_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 35309; INDEX_de8cslTo47 < 35309 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(19)->addWork(f_20_de8cslTo47);
	auto f_21_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 37167; INDEX_de8cslTo47 < 37167 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(20)->addWork(f_21_de8cslTo47);
	auto f_22_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 39025; INDEX_de8cslTo47 < 39025 + 1858; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(21)->addWork(f_22_de8cslTo47);
	auto f_23_de8cslTo47 = [&] () {
		for (size_t INDEX_de8cslTo47 = 40883; INDEX_de8cslTo47 < 40883 + 1881; ++INDEX_de8cslTo47) {
			dists_DrLizMW2Tx[(INDEX_de8cslTo47)] = sqrt((lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_de8cslTo47)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_de8cslTo47)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(22)->addWork(f_23_de8cslTo47);
	ii_tSOGPfMTth_uSZXO80NHP++;
	Bit_Mask * mask_ptr_tu61hIU8zC = new Bit_Mask(47,true);
	for (size_t i_XcjlldheTi = 0; i_XcjlldheTi < 23; ++i_XcjlldheTi) {
		mask_ptr_tu61hIU8zC->setBarrier(i_XcjlldheTi);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_tu61hIU8zC (mask_ptr_tu61hIU8zC);
	self_barrier(boost_mask_ptr_tu61hIU8zC);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_HfIAUAz4PZ[(j)] > max_val) {
				max_val = neighbor_dist_HfIAUAz4PZ[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_DrLizMW2Tx[(i)]) {
			neighbor_dist_HfIAUAz4PZ[(max_id)] = dists_DrLizMW2Tx[(i)];
			neighbor_id_QDQN1MrBKf[(max_id)] = i;
		}
	}
	time[2] = get_time() - time[2];
if ((ii_tSOGPfMTth_uSZXO80NHP == 0)) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 1) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_tSOGPfMTth_uSZXO80NHP == 2) {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_GUQVOlW7KC, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_tJnUPyK0mL, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[3] = get_time();
auto f_1_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 0; INDEX_sDRSDsxdWP < 0 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(0)->addWork(f_1_sDRSDsxdWP);
	auto f_2_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 1859; INDEX_sDRSDsxdWP < 1859 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(1)->addWork(f_2_sDRSDsxdWP);
	auto f_3_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 3718; INDEX_sDRSDsxdWP < 3718 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(2)->addWork(f_3_sDRSDsxdWP);
	auto f_4_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 5577; INDEX_sDRSDsxdWP < 5577 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(3)->addWork(f_4_sDRSDsxdWP);
	auto f_5_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 7436; INDEX_sDRSDsxdWP < 7436 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(4)->addWork(f_5_sDRSDsxdWP);
	auto f_6_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 9295; INDEX_sDRSDsxdWP < 9295 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(5)->addWork(f_6_sDRSDsxdWP);
	auto f_7_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 11154; INDEX_sDRSDsxdWP < 11154 + 1859; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(6)->addWork(f_7_sDRSDsxdWP);
	auto f_8_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 13013; INDEX_sDRSDsxdWP < 13013 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(7)->addWork(f_8_sDRSDsxdWP);
	auto f_9_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 14871; INDEX_sDRSDsxdWP < 14871 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(8)->addWork(f_9_sDRSDsxdWP);
	auto f_10_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 16729; INDEX_sDRSDsxdWP < 16729 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(9)->addWork(f_10_sDRSDsxdWP);
	auto f_11_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 18587; INDEX_sDRSDsxdWP < 18587 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(10)->addWork(f_11_sDRSDsxdWP);
	auto f_12_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 20445; INDEX_sDRSDsxdWP < 20445 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(11)->addWork(f_12_sDRSDsxdWP);
	auto f_13_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 22303; INDEX_sDRSDsxdWP < 22303 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(12)->addWork(f_13_sDRSDsxdWP);
	auto f_14_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 24161; INDEX_sDRSDsxdWP < 24161 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(13)->addWork(f_14_sDRSDsxdWP);
	auto f_15_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 26019; INDEX_sDRSDsxdWP < 26019 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(14)->addWork(f_15_sDRSDsxdWP);
	auto f_16_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 27877; INDEX_sDRSDsxdWP < 27877 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(15)->addWork(f_16_sDRSDsxdWP);
	auto f_17_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 29735; INDEX_sDRSDsxdWP < 29735 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(16)->addWork(f_17_sDRSDsxdWP);
	auto f_18_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 31593; INDEX_sDRSDsxdWP < 31593 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(17)->addWork(f_18_sDRSDsxdWP);
	auto f_19_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 33451; INDEX_sDRSDsxdWP < 33451 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(18)->addWork(f_19_sDRSDsxdWP);
	auto f_20_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 35309; INDEX_sDRSDsxdWP < 35309 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(19)->addWork(f_20_sDRSDsxdWP);
	auto f_21_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 37167; INDEX_sDRSDsxdWP < 37167 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(20)->addWork(f_21_sDRSDsxdWP);
	auto f_22_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 39025; INDEX_sDRSDsxdWP < 39025 + 1858; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(21)->addWork(f_22_sDRSDsxdWP);
	auto f_23_sDRSDsxdWP = [&] () {
		for (size_t INDEX_sDRSDsxdWP = 40883; INDEX_sDRSDsxdWP < 40883 + 1881; ++INDEX_sDRSDsxdWP) {
			dists_DrLizMW2Tx[(INDEX_sDRSDsxdWP)] = sqrt((lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) * (lon_GUQVOlW7KC[(INDEX_sDRSDsxdWP)] - target_lon_APY3Ai6raf) + (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ) * (lat_tJnUPyK0mL[(INDEX_sDRSDsxdWP)] - target_lat_kx4lgNzClJ));
		}
	};
	getPool()->at(22)->addWork(f_23_sDRSDsxdWP);
	ii_tSOGPfMTth_uSZXO80NHP++;
	Bit_Mask * mask_ptr_8pB3Mdx9ml = new Bit_Mask(47,true);
	for (size_t i_0yZWQbinbE = 0; i_0yZWQbinbE < 23; ++i_0yZWQbinbE) {
		mask_ptr_8pB3Mdx9ml->setBarrier(i_0yZWQbinbE);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_8pB3Mdx9ml (mask_ptr_8pB3Mdx9ml);
	self_barrier(boost_mask_ptr_8pB3Mdx9ml);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_HfIAUAz4PZ[(j)] > max_val) {
				max_val = neighbor_dist_HfIAUAz4PZ[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_DrLizMW2Tx[(i)]) {
			neighbor_dist_HfIAUAz4PZ[(max_id)] = dists_DrLizMW2Tx[(i)];
			neighbor_id_QDQN1MrBKf[(max_id)] = i;
		}
	}
	time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_HfIAUAz4PZ, 1LL * 5);
	array_write("canes.txt", neighbor_id_QDQN1MrBKf, 1LL * 5);
	finishExecution();
	finishGPUExecution();
	std::free(lon_GUQVOlW7KC);
	std::free(neighbor_dist_HfIAUAz4PZ);
	std::free(times_YDfvo4KzDv);
	std::free(neighbor_id_QDQN1MrBKf);
	std::free(lat_tJnUPyK0mL);
	std::free(dists_DrLizMW2Tx);
	return 0;


}

