/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_g_1.hxx"
#include "includes/cuda_lib_nn_g_1.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	int32_t ii_DMUyK6p1xJ_B4QarseC9g;
	float* lon_zQBN6kp0vt;
	float* neighbor_dist_fmRDmGK0Gf;
	int64_t* times_dcCecTrzXc;
	int32_t* neighbor_id_JDMXoLQnfo;
	float target_lat_Rp4e0gj0PZ;
	float target_lon_rMJfszh71L;
	float* lat_RHhUUztdUB;
	float* dists_MbkLzR8gJA;
	int NUM_CORES;
	int NUM_GPUS;

	NUM_CORES = 47;
	NUM_GPUS = 0;
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_fmRDmGK0Gf = Init_List(100000, neighbor_dist_fmRDmGK0Gf, 5LL * 1LL);
	dists_MbkLzR8gJA = Init_List(dists_MbkLzR8gJA, 42764LL * 1LL);
	lon_zQBN6kp0vt = Init_List(lon_zQBN6kp0vt, 42764LL * 1LL);
	neighbor_id_JDMXoLQnfo = Init_List(neighbor_id_JDMXoLQnfo, 5LL * 1LL);
	times_dcCecTrzXc = Init_List(times_dcCecTrzXc, 4LL * 1LL);
	lat_RHhUUztdUB = Init_List(lat_RHhUUztdUB, 42764LL * 1LL);
	ii_DMUyK6p1xJ_B4QarseC9g = 0;
	target_lon_rMJfszh71L = 90;
	target_lat_Rp4e0gj0PZ = 30;
	
if ((ii_DMUyK6p1xJ_B4QarseC9g == 0)) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 1) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 2) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[0] = get_time();
auto f_1_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 0; INDEX_kWX0d0hFhS < 0 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(0)->addWork(f_1_kWX0d0hFhS);
	auto f_2_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 1859; INDEX_kWX0d0hFhS < 1859 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(1)->addWork(f_2_kWX0d0hFhS);
	auto f_3_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 3718; INDEX_kWX0d0hFhS < 3718 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(2)->addWork(f_3_kWX0d0hFhS);
	auto f_4_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 5577; INDEX_kWX0d0hFhS < 5577 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(3)->addWork(f_4_kWX0d0hFhS);
	auto f_5_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 7436; INDEX_kWX0d0hFhS < 7436 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(4)->addWork(f_5_kWX0d0hFhS);
	auto f_6_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 9295; INDEX_kWX0d0hFhS < 9295 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(5)->addWork(f_6_kWX0d0hFhS);
	auto f_7_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 11154; INDEX_kWX0d0hFhS < 11154 + 1859; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(6)->addWork(f_7_kWX0d0hFhS);
	auto f_8_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 13013; INDEX_kWX0d0hFhS < 13013 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(7)->addWork(f_8_kWX0d0hFhS);
	auto f_9_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 14871; INDEX_kWX0d0hFhS < 14871 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(8)->addWork(f_9_kWX0d0hFhS);
	auto f_10_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 16729; INDEX_kWX0d0hFhS < 16729 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(9)->addWork(f_10_kWX0d0hFhS);
	auto f_11_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 18587; INDEX_kWX0d0hFhS < 18587 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(10)->addWork(f_11_kWX0d0hFhS);
	auto f_12_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 20445; INDEX_kWX0d0hFhS < 20445 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(11)->addWork(f_12_kWX0d0hFhS);
	auto f_13_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 22303; INDEX_kWX0d0hFhS < 22303 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(12)->addWork(f_13_kWX0d0hFhS);
	auto f_14_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 24161; INDEX_kWX0d0hFhS < 24161 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(13)->addWork(f_14_kWX0d0hFhS);
	auto f_15_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 26019; INDEX_kWX0d0hFhS < 26019 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(14)->addWork(f_15_kWX0d0hFhS);
	auto f_16_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 27877; INDEX_kWX0d0hFhS < 27877 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(15)->addWork(f_16_kWX0d0hFhS);
	auto f_17_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 29735; INDEX_kWX0d0hFhS < 29735 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(16)->addWork(f_17_kWX0d0hFhS);
	auto f_18_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 31593; INDEX_kWX0d0hFhS < 31593 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(17)->addWork(f_18_kWX0d0hFhS);
	auto f_19_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 33451; INDEX_kWX0d0hFhS < 33451 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(18)->addWork(f_19_kWX0d0hFhS);
	auto f_20_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 35309; INDEX_kWX0d0hFhS < 35309 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(19)->addWork(f_20_kWX0d0hFhS);
	auto f_21_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 37167; INDEX_kWX0d0hFhS < 37167 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(20)->addWork(f_21_kWX0d0hFhS);
	auto f_22_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 39025; INDEX_kWX0d0hFhS < 39025 + 1858; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(21)->addWork(f_22_kWX0d0hFhS);
	auto f_23_kWX0d0hFhS = [&] () {
		for (size_t INDEX_kWX0d0hFhS = 40883; INDEX_kWX0d0hFhS < 40883 + 1881; ++INDEX_kWX0d0hFhS) {
			dists_MbkLzR8gJA[(INDEX_kWX0d0hFhS)] = sqrt((lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_kWX0d0hFhS)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_kWX0d0hFhS)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(22)->addWork(f_23_kWX0d0hFhS);
	ii_DMUyK6p1xJ_B4QarseC9g++;
	Bit_Mask * mask_ptr_8ZtZHrDxCa = new Bit_Mask(47,true);
	for (size_t i_GBXpQc2VO1 = 0; i_GBXpQc2VO1 < 23; ++i_GBXpQc2VO1) {
		mask_ptr_8ZtZHrDxCa->setBarrier(i_GBXpQc2VO1);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_8ZtZHrDxCa (mask_ptr_8ZtZHrDxCa);
	self_barrier(boost_mask_ptr_8ZtZHrDxCa);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_fmRDmGK0Gf[(j)] > max_val) {
				max_val = neighbor_dist_fmRDmGK0Gf[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_MbkLzR8gJA[(i)]) {
			neighbor_dist_fmRDmGK0Gf[(max_id)] = dists_MbkLzR8gJA[(i)];
			neighbor_id_JDMXoLQnfo[(max_id)] = i;
		}
	}
	time[0] = get_time() - time[0];
if ((ii_DMUyK6p1xJ_B4QarseC9g == 0)) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 1) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 2) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[1] = get_time();
auto f_1_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 0; INDEX_zJaO1fpRTE < 0 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(0)->addWork(f_1_zJaO1fpRTE);
	auto f_2_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 1859; INDEX_zJaO1fpRTE < 1859 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(1)->addWork(f_2_zJaO1fpRTE);
	auto f_3_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 3718; INDEX_zJaO1fpRTE < 3718 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(2)->addWork(f_3_zJaO1fpRTE);
	auto f_4_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 5577; INDEX_zJaO1fpRTE < 5577 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(3)->addWork(f_4_zJaO1fpRTE);
	auto f_5_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 7436; INDEX_zJaO1fpRTE < 7436 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(4)->addWork(f_5_zJaO1fpRTE);
	auto f_6_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 9295; INDEX_zJaO1fpRTE < 9295 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(5)->addWork(f_6_zJaO1fpRTE);
	auto f_7_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 11154; INDEX_zJaO1fpRTE < 11154 + 1859; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(6)->addWork(f_7_zJaO1fpRTE);
	auto f_8_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 13013; INDEX_zJaO1fpRTE < 13013 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(7)->addWork(f_8_zJaO1fpRTE);
	auto f_9_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 14871; INDEX_zJaO1fpRTE < 14871 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(8)->addWork(f_9_zJaO1fpRTE);
	auto f_10_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 16729; INDEX_zJaO1fpRTE < 16729 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(9)->addWork(f_10_zJaO1fpRTE);
	auto f_11_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 18587; INDEX_zJaO1fpRTE < 18587 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(10)->addWork(f_11_zJaO1fpRTE);
	auto f_12_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 20445; INDEX_zJaO1fpRTE < 20445 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(11)->addWork(f_12_zJaO1fpRTE);
	auto f_13_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 22303; INDEX_zJaO1fpRTE < 22303 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(12)->addWork(f_13_zJaO1fpRTE);
	auto f_14_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 24161; INDEX_zJaO1fpRTE < 24161 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(13)->addWork(f_14_zJaO1fpRTE);
	auto f_15_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 26019; INDEX_zJaO1fpRTE < 26019 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(14)->addWork(f_15_zJaO1fpRTE);
	auto f_16_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 27877; INDEX_zJaO1fpRTE < 27877 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(15)->addWork(f_16_zJaO1fpRTE);
	auto f_17_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 29735; INDEX_zJaO1fpRTE < 29735 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(16)->addWork(f_17_zJaO1fpRTE);
	auto f_18_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 31593; INDEX_zJaO1fpRTE < 31593 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(17)->addWork(f_18_zJaO1fpRTE);
	auto f_19_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 33451; INDEX_zJaO1fpRTE < 33451 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(18)->addWork(f_19_zJaO1fpRTE);
	auto f_20_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 35309; INDEX_zJaO1fpRTE < 35309 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(19)->addWork(f_20_zJaO1fpRTE);
	auto f_21_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 37167; INDEX_zJaO1fpRTE < 37167 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(20)->addWork(f_21_zJaO1fpRTE);
	auto f_22_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 39025; INDEX_zJaO1fpRTE < 39025 + 1858; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(21)->addWork(f_22_zJaO1fpRTE);
	auto f_23_zJaO1fpRTE = [&] () {
		for (size_t INDEX_zJaO1fpRTE = 40883; INDEX_zJaO1fpRTE < 40883 + 1881; ++INDEX_zJaO1fpRTE) {
			dists_MbkLzR8gJA[(INDEX_zJaO1fpRTE)] = sqrt((lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_zJaO1fpRTE)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_zJaO1fpRTE)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(22)->addWork(f_23_zJaO1fpRTE);
	ii_DMUyK6p1xJ_B4QarseC9g++;
	time[1] = get_time() - time[1];
if ((ii_DMUyK6p1xJ_B4QarseC9g == 0)) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 1) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 2) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	Bit_Mask * mask_ptr_6yDzqVEVeU = new Bit_Mask(47,true);
	for (size_t i_VgxRHncQeH = 0; i_VgxRHncQeH < 23; ++i_VgxRHncQeH) {
		mask_ptr_6yDzqVEVeU->setBarrier(i_VgxRHncQeH);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_6yDzqVEVeU (mask_ptr_6yDzqVEVeU);
	self_barrier(boost_mask_ptr_6yDzqVEVeU);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_fmRDmGK0Gf[(j)] > max_val) {
				max_val = neighbor_dist_fmRDmGK0Gf[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_MbkLzR8gJA[(i)]) {
			neighbor_dist_fmRDmGK0Gf[(max_id)] = dists_MbkLzR8gJA[(i)];
			neighbor_id_JDMXoLQnfo[(max_id)] = i;
		}
	}
	time[2] = get_time();
auto f_1_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 0; INDEX_lD48KGzVnC < 0 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(0)->addWork(f_1_lD48KGzVnC);
	auto f_2_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 1859; INDEX_lD48KGzVnC < 1859 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(1)->addWork(f_2_lD48KGzVnC);
	auto f_3_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 3718; INDEX_lD48KGzVnC < 3718 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(2)->addWork(f_3_lD48KGzVnC);
	auto f_4_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 5577; INDEX_lD48KGzVnC < 5577 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(3)->addWork(f_4_lD48KGzVnC);
	auto f_5_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 7436; INDEX_lD48KGzVnC < 7436 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(4)->addWork(f_5_lD48KGzVnC);
	auto f_6_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 9295; INDEX_lD48KGzVnC < 9295 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(5)->addWork(f_6_lD48KGzVnC);
	auto f_7_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 11154; INDEX_lD48KGzVnC < 11154 + 1859; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(6)->addWork(f_7_lD48KGzVnC);
	auto f_8_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 13013; INDEX_lD48KGzVnC < 13013 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(7)->addWork(f_8_lD48KGzVnC);
	auto f_9_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 14871; INDEX_lD48KGzVnC < 14871 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(8)->addWork(f_9_lD48KGzVnC);
	auto f_10_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 16729; INDEX_lD48KGzVnC < 16729 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(9)->addWork(f_10_lD48KGzVnC);
	auto f_11_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 18587; INDEX_lD48KGzVnC < 18587 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(10)->addWork(f_11_lD48KGzVnC);
	auto f_12_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 20445; INDEX_lD48KGzVnC < 20445 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(11)->addWork(f_12_lD48KGzVnC);
	auto f_13_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 22303; INDEX_lD48KGzVnC < 22303 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(12)->addWork(f_13_lD48KGzVnC);
	auto f_14_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 24161; INDEX_lD48KGzVnC < 24161 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(13)->addWork(f_14_lD48KGzVnC);
	auto f_15_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 26019; INDEX_lD48KGzVnC < 26019 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(14)->addWork(f_15_lD48KGzVnC);
	auto f_16_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 27877; INDEX_lD48KGzVnC < 27877 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(15)->addWork(f_16_lD48KGzVnC);
	auto f_17_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 29735; INDEX_lD48KGzVnC < 29735 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(16)->addWork(f_17_lD48KGzVnC);
	auto f_18_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 31593; INDEX_lD48KGzVnC < 31593 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(17)->addWork(f_18_lD48KGzVnC);
	auto f_19_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 33451; INDEX_lD48KGzVnC < 33451 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(18)->addWork(f_19_lD48KGzVnC);
	auto f_20_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 35309; INDEX_lD48KGzVnC < 35309 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(19)->addWork(f_20_lD48KGzVnC);
	auto f_21_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 37167; INDEX_lD48KGzVnC < 37167 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(20)->addWork(f_21_lD48KGzVnC);
	auto f_22_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 39025; INDEX_lD48KGzVnC < 39025 + 1858; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(21)->addWork(f_22_lD48KGzVnC);
	auto f_23_lD48KGzVnC = [&] () {
		for (size_t INDEX_lD48KGzVnC = 40883; INDEX_lD48KGzVnC < 40883 + 1881; ++INDEX_lD48KGzVnC) {
			dists_MbkLzR8gJA[(INDEX_lD48KGzVnC)] = sqrt((lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_lD48KGzVnC)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_lD48KGzVnC)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(22)->addWork(f_23_lD48KGzVnC);
	ii_DMUyK6p1xJ_B4QarseC9g++;
	Bit_Mask * mask_ptr_JkYPFh9AR8 = new Bit_Mask(47,true);
	for (size_t i_xCJyULtbfK = 0; i_xCJyULtbfK < 23; ++i_xCJyULtbfK) {
		mask_ptr_JkYPFh9AR8->setBarrier(i_xCJyULtbfK);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_JkYPFh9AR8 (mask_ptr_JkYPFh9AR8);
	self_barrier(boost_mask_ptr_JkYPFh9AR8);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_fmRDmGK0Gf[(j)] > max_val) {
				max_val = neighbor_dist_fmRDmGK0Gf[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_MbkLzR8gJA[(i)]) {
			neighbor_dist_fmRDmGK0Gf[(max_id)] = dists_MbkLzR8gJA[(i)];
			neighbor_id_JDMXoLQnfo[(max_id)] = i;
		}
	}
	time[2] = get_time() - time[2];
if ((ii_DMUyK6p1xJ_B4QarseC9g == 0)) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 1) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_DMUyK6p1xJ_B4QarseC9g == 2) {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_zQBN6kp0vt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_RHhUUztdUB, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[3] = get_time();
auto f_1_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 0; INDEX_rxgMvfi511 < 0 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(0)->addWork(f_1_rxgMvfi511);
	auto f_2_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 1859; INDEX_rxgMvfi511 < 1859 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(1)->addWork(f_2_rxgMvfi511);
	auto f_3_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 3718; INDEX_rxgMvfi511 < 3718 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(2)->addWork(f_3_rxgMvfi511);
	auto f_4_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 5577; INDEX_rxgMvfi511 < 5577 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(3)->addWork(f_4_rxgMvfi511);
	auto f_5_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 7436; INDEX_rxgMvfi511 < 7436 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(4)->addWork(f_5_rxgMvfi511);
	auto f_6_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 9295; INDEX_rxgMvfi511 < 9295 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(5)->addWork(f_6_rxgMvfi511);
	auto f_7_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 11154; INDEX_rxgMvfi511 < 11154 + 1859; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(6)->addWork(f_7_rxgMvfi511);
	auto f_8_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 13013; INDEX_rxgMvfi511 < 13013 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(7)->addWork(f_8_rxgMvfi511);
	auto f_9_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 14871; INDEX_rxgMvfi511 < 14871 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(8)->addWork(f_9_rxgMvfi511);
	auto f_10_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 16729; INDEX_rxgMvfi511 < 16729 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(9)->addWork(f_10_rxgMvfi511);
	auto f_11_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 18587; INDEX_rxgMvfi511 < 18587 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(10)->addWork(f_11_rxgMvfi511);
	auto f_12_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 20445; INDEX_rxgMvfi511 < 20445 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(11)->addWork(f_12_rxgMvfi511);
	auto f_13_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 22303; INDEX_rxgMvfi511 < 22303 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(12)->addWork(f_13_rxgMvfi511);
	auto f_14_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 24161; INDEX_rxgMvfi511 < 24161 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(13)->addWork(f_14_rxgMvfi511);
	auto f_15_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 26019; INDEX_rxgMvfi511 < 26019 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(14)->addWork(f_15_rxgMvfi511);
	auto f_16_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 27877; INDEX_rxgMvfi511 < 27877 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(15)->addWork(f_16_rxgMvfi511);
	auto f_17_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 29735; INDEX_rxgMvfi511 < 29735 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(16)->addWork(f_17_rxgMvfi511);
	auto f_18_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 31593; INDEX_rxgMvfi511 < 31593 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(17)->addWork(f_18_rxgMvfi511);
	auto f_19_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 33451; INDEX_rxgMvfi511 < 33451 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(18)->addWork(f_19_rxgMvfi511);
	auto f_20_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 35309; INDEX_rxgMvfi511 < 35309 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(19)->addWork(f_20_rxgMvfi511);
	auto f_21_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 37167; INDEX_rxgMvfi511 < 37167 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(20)->addWork(f_21_rxgMvfi511);
	auto f_22_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 39025; INDEX_rxgMvfi511 < 39025 + 1858; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(21)->addWork(f_22_rxgMvfi511);
	auto f_23_rxgMvfi511 = [&] () {
		for (size_t INDEX_rxgMvfi511 = 40883; INDEX_rxgMvfi511 < 40883 + 1881; ++INDEX_rxgMvfi511) {
			dists_MbkLzR8gJA[(INDEX_rxgMvfi511)] = sqrt((lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) * (lon_zQBN6kp0vt[(INDEX_rxgMvfi511)] - target_lon_rMJfszh71L) + (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ) * (lat_RHhUUztdUB[(INDEX_rxgMvfi511)] - target_lat_Rp4e0gj0PZ));
		}
	};
	getPool()->at(22)->addWork(f_23_rxgMvfi511);
	ii_DMUyK6p1xJ_B4QarseC9g++;
	Bit_Mask * mask_ptr_hkWrdQyyRO = new Bit_Mask(47,true);
	for (size_t i_u8ZsBAE0ZO = 0; i_u8ZsBAE0ZO < 23; ++i_u8ZsBAE0ZO) {
		mask_ptr_hkWrdQyyRO->setBarrier(i_u8ZsBAE0ZO);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_hkWrdQyyRO (mask_ptr_hkWrdQyyRO);
	self_barrier(boost_mask_ptr_hkWrdQyyRO);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_fmRDmGK0Gf[(j)] > max_val) {
				max_val = neighbor_dist_fmRDmGK0Gf[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_MbkLzR8gJA[(i)]) {
			neighbor_dist_fmRDmGK0Gf[(max_id)] = dists_MbkLzR8gJA[(i)];
			neighbor_id_JDMXoLQnfo[(max_id)] = i;
		}
	}
	time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_fmRDmGK0Gf, 1LL * 5);
	array_write("canes.txt", neighbor_id_JDMXoLQnfo, 1LL * 5);
	finishExecution();
	finishGPUExecution();
	std::free(lon_zQBN6kp0vt);
	std::free(neighbor_dist_fmRDmGK0Gf);
	std::free(times_dcCecTrzXc);
	std::free(neighbor_id_JDMXoLQnfo);
	std::free(lat_RHhUUztdUB);
	std::free(dists_MbkLzR8gJA);
	return 0;


}

