/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_m_1.hxx"
#include "includes/cuda_lib_nn_m_1.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	int32_t ii_HuZ6vamjSG_mYLlRBU5s9;
	float* lon_BdrtGQTNvt;
	float* neighbor_dist_LIRb3iemZP;
	int64_t* times_o9DIiQRchL;
	int32_t* neighbor_id_leWkhHk6su;
	float target_lat_DIXQQJ8W2e;
	float target_lon_qYkgblGj2K;
	float* lat_i78P3CV2H4;
	float* dists_jlHyT0xEuQ;
	int NUM_CORES;
	int NUM_GPUS;

	NUM_CORES = 47;
	NUM_GPUS = 0;
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_LIRb3iemZP = Init_List(100000, neighbor_dist_LIRb3iemZP, 5LL * 1LL);
	dists_jlHyT0xEuQ = Init_List(dists_jlHyT0xEuQ, 42764LL * 1LL);
	lon_BdrtGQTNvt = Init_List(lon_BdrtGQTNvt, 42764LL * 1LL);
	neighbor_id_leWkhHk6su = Init_List(neighbor_id_leWkhHk6su, 5LL * 1LL);
	times_o9DIiQRchL = Init_List(times_o9DIiQRchL, 4LL * 1LL);
	lat_i78P3CV2H4 = Init_List(lat_i78P3CV2H4, 42764LL * 1LL);
	ii_HuZ6vamjSG_mYLlRBU5s9 = 0;
	target_lon_qYkgblGj2K = 90;
	target_lat_DIXQQJ8W2e = 30;
	
if ((ii_HuZ6vamjSG_mYLlRBU5s9 == 0)) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 1) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 2) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[0] = get_time();
auto f_1_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 0; INDEX_TnTLW2msbm < 0 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(0)->addWork(f_1_TnTLW2msbm);
	auto f_2_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 1859; INDEX_TnTLW2msbm < 1859 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(1)->addWork(f_2_TnTLW2msbm);
	auto f_3_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 3718; INDEX_TnTLW2msbm < 3718 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(2)->addWork(f_3_TnTLW2msbm);
	auto f_4_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 5577; INDEX_TnTLW2msbm < 5577 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(3)->addWork(f_4_TnTLW2msbm);
	auto f_5_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 7436; INDEX_TnTLW2msbm < 7436 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(4)->addWork(f_5_TnTLW2msbm);
	auto f_6_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 9295; INDEX_TnTLW2msbm < 9295 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(5)->addWork(f_6_TnTLW2msbm);
	auto f_7_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 11154; INDEX_TnTLW2msbm < 11154 + 1859; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(6)->addWork(f_7_TnTLW2msbm);
	auto f_8_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 13013; INDEX_TnTLW2msbm < 13013 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(7)->addWork(f_8_TnTLW2msbm);
	auto f_9_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 14871; INDEX_TnTLW2msbm < 14871 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(8)->addWork(f_9_TnTLW2msbm);
	auto f_10_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 16729; INDEX_TnTLW2msbm < 16729 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(9)->addWork(f_10_TnTLW2msbm);
	auto f_11_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 18587; INDEX_TnTLW2msbm < 18587 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(10)->addWork(f_11_TnTLW2msbm);
	auto f_12_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 20445; INDEX_TnTLW2msbm < 20445 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(11)->addWork(f_12_TnTLW2msbm);
	auto f_13_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 22303; INDEX_TnTLW2msbm < 22303 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(12)->addWork(f_13_TnTLW2msbm);
	auto f_14_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 24161; INDEX_TnTLW2msbm < 24161 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(13)->addWork(f_14_TnTLW2msbm);
	auto f_15_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 26019; INDEX_TnTLW2msbm < 26019 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(14)->addWork(f_15_TnTLW2msbm);
	auto f_16_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 27877; INDEX_TnTLW2msbm < 27877 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(15)->addWork(f_16_TnTLW2msbm);
	auto f_17_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 29735; INDEX_TnTLW2msbm < 29735 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(16)->addWork(f_17_TnTLW2msbm);
	auto f_18_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 31593; INDEX_TnTLW2msbm < 31593 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(17)->addWork(f_18_TnTLW2msbm);
	auto f_19_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 33451; INDEX_TnTLW2msbm < 33451 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(18)->addWork(f_19_TnTLW2msbm);
	auto f_20_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 35309; INDEX_TnTLW2msbm < 35309 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(19)->addWork(f_20_TnTLW2msbm);
	auto f_21_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 37167; INDEX_TnTLW2msbm < 37167 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(20)->addWork(f_21_TnTLW2msbm);
	auto f_22_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 39025; INDEX_TnTLW2msbm < 39025 + 1858; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(21)->addWork(f_22_TnTLW2msbm);
	auto f_23_TnTLW2msbm = [&] () {
		for (size_t INDEX_TnTLW2msbm = 40883; INDEX_TnTLW2msbm < 40883 + 1881; ++INDEX_TnTLW2msbm) {
			dists_jlHyT0xEuQ[(INDEX_TnTLW2msbm)] = sqrt((lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_TnTLW2msbm)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_TnTLW2msbm)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(22)->addWork(f_23_TnTLW2msbm);
	ii_HuZ6vamjSG_mYLlRBU5s9++;
	Bit_Mask * mask_ptr_c5nILn6C1a = new Bit_Mask(47,true);
	for (size_t i_XQDqjUq22D = 0; i_XQDqjUq22D < 23; ++i_XQDqjUq22D) {
		mask_ptr_c5nILn6C1a->setBarrier(i_XQDqjUq22D);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_c5nILn6C1a (mask_ptr_c5nILn6C1a);
	self_barrier(boost_mask_ptr_c5nILn6C1a);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_LIRb3iemZP[(j)] > max_val) {
				max_val = neighbor_dist_LIRb3iemZP[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jlHyT0xEuQ[(i)]) {
			neighbor_dist_LIRb3iemZP[(max_id)] = dists_jlHyT0xEuQ[(i)];
			neighbor_id_leWkhHk6su[(max_id)] = i;
		}
	}
	time[0] = get_time() - time[0];
if ((ii_HuZ6vamjSG_mYLlRBU5s9 == 0)) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 1) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 2) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[1] = get_time();
auto f_1_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 0; INDEX_MfDhzqGHhW < 0 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(0)->addWork(f_1_MfDhzqGHhW);
	auto f_2_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 1859; INDEX_MfDhzqGHhW < 1859 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(1)->addWork(f_2_MfDhzqGHhW);
	auto f_3_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 3718; INDEX_MfDhzqGHhW < 3718 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(2)->addWork(f_3_MfDhzqGHhW);
	auto f_4_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 5577; INDEX_MfDhzqGHhW < 5577 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(3)->addWork(f_4_MfDhzqGHhW);
	auto f_5_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 7436; INDEX_MfDhzqGHhW < 7436 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(4)->addWork(f_5_MfDhzqGHhW);
	auto f_6_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 9295; INDEX_MfDhzqGHhW < 9295 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(5)->addWork(f_6_MfDhzqGHhW);
	auto f_7_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 11154; INDEX_MfDhzqGHhW < 11154 + 1859; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(6)->addWork(f_7_MfDhzqGHhW);
	auto f_8_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 13013; INDEX_MfDhzqGHhW < 13013 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(7)->addWork(f_8_MfDhzqGHhW);
	auto f_9_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 14871; INDEX_MfDhzqGHhW < 14871 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(8)->addWork(f_9_MfDhzqGHhW);
	auto f_10_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 16729; INDEX_MfDhzqGHhW < 16729 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(9)->addWork(f_10_MfDhzqGHhW);
	auto f_11_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 18587; INDEX_MfDhzqGHhW < 18587 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(10)->addWork(f_11_MfDhzqGHhW);
	auto f_12_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 20445; INDEX_MfDhzqGHhW < 20445 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(11)->addWork(f_12_MfDhzqGHhW);
	auto f_13_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 22303; INDEX_MfDhzqGHhW < 22303 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(12)->addWork(f_13_MfDhzqGHhW);
	auto f_14_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 24161; INDEX_MfDhzqGHhW < 24161 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(13)->addWork(f_14_MfDhzqGHhW);
	auto f_15_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 26019; INDEX_MfDhzqGHhW < 26019 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(14)->addWork(f_15_MfDhzqGHhW);
	auto f_16_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 27877; INDEX_MfDhzqGHhW < 27877 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(15)->addWork(f_16_MfDhzqGHhW);
	auto f_17_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 29735; INDEX_MfDhzqGHhW < 29735 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(16)->addWork(f_17_MfDhzqGHhW);
	auto f_18_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 31593; INDEX_MfDhzqGHhW < 31593 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(17)->addWork(f_18_MfDhzqGHhW);
	auto f_19_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 33451; INDEX_MfDhzqGHhW < 33451 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(18)->addWork(f_19_MfDhzqGHhW);
	auto f_20_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 35309; INDEX_MfDhzqGHhW < 35309 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(19)->addWork(f_20_MfDhzqGHhW);
	auto f_21_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 37167; INDEX_MfDhzqGHhW < 37167 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(20)->addWork(f_21_MfDhzqGHhW);
	auto f_22_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 39025; INDEX_MfDhzqGHhW < 39025 + 1858; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(21)->addWork(f_22_MfDhzqGHhW);
	auto f_23_MfDhzqGHhW = [&] () {
		for (size_t INDEX_MfDhzqGHhW = 40883; INDEX_MfDhzqGHhW < 40883 + 1881; ++INDEX_MfDhzqGHhW) {
			dists_jlHyT0xEuQ[(INDEX_MfDhzqGHhW)] = sqrt((lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_MfDhzqGHhW)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_MfDhzqGHhW)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(22)->addWork(f_23_MfDhzqGHhW);
	ii_HuZ6vamjSG_mYLlRBU5s9++;
	time[1] = get_time() - time[1];
if ((ii_HuZ6vamjSG_mYLlRBU5s9 == 0)) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 1) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 2) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	Bit_Mask * mask_ptr_7d0ekk1fBV = new Bit_Mask(47,true);
	for (size_t i_UA2rhN1Oqg = 0; i_UA2rhN1Oqg < 23; ++i_UA2rhN1Oqg) {
		mask_ptr_7d0ekk1fBV->setBarrier(i_UA2rhN1Oqg);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_7d0ekk1fBV (mask_ptr_7d0ekk1fBV);
	self_barrier(boost_mask_ptr_7d0ekk1fBV);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_LIRb3iemZP[(j)] > max_val) {
				max_val = neighbor_dist_LIRb3iemZP[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jlHyT0xEuQ[(i)]) {
			neighbor_dist_LIRb3iemZP[(max_id)] = dists_jlHyT0xEuQ[(i)];
			neighbor_id_leWkhHk6su[(max_id)] = i;
		}
	}
	time[2] = get_time();
auto f_1_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 0; INDEX_f64WFjgpqe < 0 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(0)->addWork(f_1_f64WFjgpqe);
	auto f_2_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 1859; INDEX_f64WFjgpqe < 1859 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(1)->addWork(f_2_f64WFjgpqe);
	auto f_3_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 3718; INDEX_f64WFjgpqe < 3718 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(2)->addWork(f_3_f64WFjgpqe);
	auto f_4_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 5577; INDEX_f64WFjgpqe < 5577 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(3)->addWork(f_4_f64WFjgpqe);
	auto f_5_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 7436; INDEX_f64WFjgpqe < 7436 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(4)->addWork(f_5_f64WFjgpqe);
	auto f_6_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 9295; INDEX_f64WFjgpqe < 9295 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(5)->addWork(f_6_f64WFjgpqe);
	auto f_7_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 11154; INDEX_f64WFjgpqe < 11154 + 1859; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(6)->addWork(f_7_f64WFjgpqe);
	auto f_8_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 13013; INDEX_f64WFjgpqe < 13013 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(7)->addWork(f_8_f64WFjgpqe);
	auto f_9_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 14871; INDEX_f64WFjgpqe < 14871 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(8)->addWork(f_9_f64WFjgpqe);
	auto f_10_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 16729; INDEX_f64WFjgpqe < 16729 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(9)->addWork(f_10_f64WFjgpqe);
	auto f_11_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 18587; INDEX_f64WFjgpqe < 18587 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(10)->addWork(f_11_f64WFjgpqe);
	auto f_12_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 20445; INDEX_f64WFjgpqe < 20445 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(11)->addWork(f_12_f64WFjgpqe);
	auto f_13_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 22303; INDEX_f64WFjgpqe < 22303 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(12)->addWork(f_13_f64WFjgpqe);
	auto f_14_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 24161; INDEX_f64WFjgpqe < 24161 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(13)->addWork(f_14_f64WFjgpqe);
	auto f_15_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 26019; INDEX_f64WFjgpqe < 26019 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(14)->addWork(f_15_f64WFjgpqe);
	auto f_16_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 27877; INDEX_f64WFjgpqe < 27877 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(15)->addWork(f_16_f64WFjgpqe);
	auto f_17_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 29735; INDEX_f64WFjgpqe < 29735 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(16)->addWork(f_17_f64WFjgpqe);
	auto f_18_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 31593; INDEX_f64WFjgpqe < 31593 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(17)->addWork(f_18_f64WFjgpqe);
	auto f_19_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 33451; INDEX_f64WFjgpqe < 33451 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(18)->addWork(f_19_f64WFjgpqe);
	auto f_20_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 35309; INDEX_f64WFjgpqe < 35309 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(19)->addWork(f_20_f64WFjgpqe);
	auto f_21_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 37167; INDEX_f64WFjgpqe < 37167 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(20)->addWork(f_21_f64WFjgpqe);
	auto f_22_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 39025; INDEX_f64WFjgpqe < 39025 + 1858; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(21)->addWork(f_22_f64WFjgpqe);
	auto f_23_f64WFjgpqe = [&] () {
		for (size_t INDEX_f64WFjgpqe = 40883; INDEX_f64WFjgpqe < 40883 + 1881; ++INDEX_f64WFjgpqe) {
			dists_jlHyT0xEuQ[(INDEX_f64WFjgpqe)] = sqrt((lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_f64WFjgpqe)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_f64WFjgpqe)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(22)->addWork(f_23_f64WFjgpqe);
	ii_HuZ6vamjSG_mYLlRBU5s9++;
	Bit_Mask * mask_ptr_gi7FG3EYpW = new Bit_Mask(47,true);
	for (size_t i_oYXiuErJMf = 0; i_oYXiuErJMf < 23; ++i_oYXiuErJMf) {
		mask_ptr_gi7FG3EYpW->setBarrier(i_oYXiuErJMf);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_gi7FG3EYpW (mask_ptr_gi7FG3EYpW);
	self_barrier(boost_mask_ptr_gi7FG3EYpW);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_LIRb3iemZP[(j)] > max_val) {
				max_val = neighbor_dist_LIRb3iemZP[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jlHyT0xEuQ[(i)]) {
			neighbor_dist_LIRb3iemZP[(max_id)] = dists_jlHyT0xEuQ[(i)];
			neighbor_id_leWkhHk6su[(max_id)] = i;
		}
	}
	time[2] = get_time() - time[2];
if ((ii_HuZ6vamjSG_mYLlRBU5s9 == 0)) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 1) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_HuZ6vamjSG_mYLlRBU5s9 == 2) {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_BdrtGQTNvt, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_i78P3CV2H4, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[3] = get_time();
auto f_1_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 0; INDEX_uj88cv9LM8 < 0 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(0)->addWork(f_1_uj88cv9LM8);
	auto f_2_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 1859; INDEX_uj88cv9LM8 < 1859 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(1)->addWork(f_2_uj88cv9LM8);
	auto f_3_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 3718; INDEX_uj88cv9LM8 < 3718 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(2)->addWork(f_3_uj88cv9LM8);
	auto f_4_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 5577; INDEX_uj88cv9LM8 < 5577 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(3)->addWork(f_4_uj88cv9LM8);
	auto f_5_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 7436; INDEX_uj88cv9LM8 < 7436 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(4)->addWork(f_5_uj88cv9LM8);
	auto f_6_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 9295; INDEX_uj88cv9LM8 < 9295 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(5)->addWork(f_6_uj88cv9LM8);
	auto f_7_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 11154; INDEX_uj88cv9LM8 < 11154 + 1859; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(6)->addWork(f_7_uj88cv9LM8);
	auto f_8_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 13013; INDEX_uj88cv9LM8 < 13013 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(7)->addWork(f_8_uj88cv9LM8);
	auto f_9_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 14871; INDEX_uj88cv9LM8 < 14871 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(8)->addWork(f_9_uj88cv9LM8);
	auto f_10_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 16729; INDEX_uj88cv9LM8 < 16729 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(9)->addWork(f_10_uj88cv9LM8);
	auto f_11_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 18587; INDEX_uj88cv9LM8 < 18587 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(10)->addWork(f_11_uj88cv9LM8);
	auto f_12_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 20445; INDEX_uj88cv9LM8 < 20445 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(11)->addWork(f_12_uj88cv9LM8);
	auto f_13_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 22303; INDEX_uj88cv9LM8 < 22303 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(12)->addWork(f_13_uj88cv9LM8);
	auto f_14_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 24161; INDEX_uj88cv9LM8 < 24161 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(13)->addWork(f_14_uj88cv9LM8);
	auto f_15_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 26019; INDEX_uj88cv9LM8 < 26019 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(14)->addWork(f_15_uj88cv9LM8);
	auto f_16_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 27877; INDEX_uj88cv9LM8 < 27877 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(15)->addWork(f_16_uj88cv9LM8);
	auto f_17_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 29735; INDEX_uj88cv9LM8 < 29735 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(16)->addWork(f_17_uj88cv9LM8);
	auto f_18_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 31593; INDEX_uj88cv9LM8 < 31593 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(17)->addWork(f_18_uj88cv9LM8);
	auto f_19_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 33451; INDEX_uj88cv9LM8 < 33451 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(18)->addWork(f_19_uj88cv9LM8);
	auto f_20_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 35309; INDEX_uj88cv9LM8 < 35309 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(19)->addWork(f_20_uj88cv9LM8);
	auto f_21_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 37167; INDEX_uj88cv9LM8 < 37167 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(20)->addWork(f_21_uj88cv9LM8);
	auto f_22_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 39025; INDEX_uj88cv9LM8 < 39025 + 1858; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(21)->addWork(f_22_uj88cv9LM8);
	auto f_23_uj88cv9LM8 = [&] () {
		for (size_t INDEX_uj88cv9LM8 = 40883; INDEX_uj88cv9LM8 < 40883 + 1881; ++INDEX_uj88cv9LM8) {
			dists_jlHyT0xEuQ[(INDEX_uj88cv9LM8)] = sqrt((lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) * (lon_BdrtGQTNvt[(INDEX_uj88cv9LM8)] - target_lon_qYkgblGj2K) + (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e) * (lat_i78P3CV2H4[(INDEX_uj88cv9LM8)] - target_lat_DIXQQJ8W2e));
		}
	};
	getPool()->at(22)->addWork(f_23_uj88cv9LM8);
	ii_HuZ6vamjSG_mYLlRBU5s9++;
	Bit_Mask * mask_ptr_otx0YYZdZS = new Bit_Mask(47,true);
	for (size_t i_BA1d21t8qk = 0; i_BA1d21t8qk < 23; ++i_BA1d21t8qk) {
		mask_ptr_otx0YYZdZS->setBarrier(i_BA1d21t8qk);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_otx0YYZdZS (mask_ptr_otx0YYZdZS);
	self_barrier(boost_mask_ptr_otx0YYZdZS);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_LIRb3iemZP[(j)] > max_val) {
				max_val = neighbor_dist_LIRb3iemZP[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jlHyT0xEuQ[(i)]) {
			neighbor_dist_LIRb3iemZP[(max_id)] = dists_jlHyT0xEuQ[(i)];
			neighbor_id_leWkhHk6su[(max_id)] = i;
		}
	}
	time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_LIRb3iemZP, 1LL * 5);
	array_write("canes.txt", neighbor_id_leWkhHk6su, 1LL * 5);
	finishExecution();
	finishGPUExecution();
	std::free(lon_BdrtGQTNvt);
	std::free(neighbor_dist_LIRb3iemZP);
	std::free(times_o9DIiQRchL);
	std::free(neighbor_id_leWkhHk6su);
	std::free(lat_i78P3CV2H4);
	std::free(dists_jlHyT0xEuQ);
	return 0;


}

