
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef nn_m_2_HXX
#define nn_m_2_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}



#endif