/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_g_2.hxx"
#include "includes/cuda_lib_nn_g_2.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	float* lon_MQs82k9kZP;
	int32_t ii_VlRUFPD0ob_cPQC8UBv5p;
	float* neighbor_dist_8tDNhYDxsV;
	int64_t* times_FTDz3FHJPz;
	int32_t* neighbor_id_IHC0dMJpg6;
	float target_lat_bcOh37UIZx;
	float target_lon_bga9uhfoWF;
	float* lat_ouEE9yLRax;
	float* dists_6eG7OrYJh4;
	int NUM_CORES;
	int NUM_GPUS;

	int rank, nprocs;
	MPI_Status Stat;
	MPI_Init(&argc, &argv);
	MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
	if (rank == 0 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	} else 	if (rank == 1 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	}
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_8tDNhYDxsV = Init_List(100000, neighbor_dist_8tDNhYDxsV, 5LL * 1LL);
	dists_6eG7OrYJh4 = Init_List(dists_6eG7OrYJh4, 42764LL * 1LL);
	lon_MQs82k9kZP = Init_List(lon_MQs82k9kZP, 42764LL * 1LL);
	neighbor_id_IHC0dMJpg6 = Init_List(neighbor_id_IHC0dMJpg6, 5LL * 1LL);
	times_FTDz3FHJPz = Init_List(times_FTDz3FHJPz, 4LL * 1LL);
	lat_ouEE9yLRax = Init_List(lat_ouEE9yLRax, 42764LL * 1LL);
	if (rank == 0) {
		ii_VlRUFPD0ob_cPQC8UBv5p = 0;
	}
	if (rank == 0) {
		target_lon_bga9uhfoWF = 90;
		target_lat_bcOh37UIZx = 30;
	}
	if (rank == 0) {
		
if ((ii_VlRUFPD0ob_cPQC8UBv5p == 0)) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 1) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 2) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[0] = get_time();
auto f_1_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 0; INDEX_OiOLCPqsuG < 0 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(0)->addWork(f_1_OiOLCPqsuG);
		auto f_2_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 1859; INDEX_OiOLCPqsuG < 1859 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(1)->addWork(f_2_OiOLCPqsuG);
		auto f_3_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 3718; INDEX_OiOLCPqsuG < 3718 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(2)->addWork(f_3_OiOLCPqsuG);
		auto f_4_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 5577; INDEX_OiOLCPqsuG < 5577 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(3)->addWork(f_4_OiOLCPqsuG);
		auto f_5_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 7436; INDEX_OiOLCPqsuG < 7436 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(4)->addWork(f_5_OiOLCPqsuG);
		auto f_6_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 9295; INDEX_OiOLCPqsuG < 9295 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(5)->addWork(f_6_OiOLCPqsuG);
		auto f_7_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 11154; INDEX_OiOLCPqsuG < 11154 + 1859; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(6)->addWork(f_7_OiOLCPqsuG);
		auto f_8_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 13013; INDEX_OiOLCPqsuG < 13013 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(7)->addWork(f_8_OiOLCPqsuG);
		auto f_9_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 14871; INDEX_OiOLCPqsuG < 14871 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(8)->addWork(f_9_OiOLCPqsuG);
		auto f_10_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 16729; INDEX_OiOLCPqsuG < 16729 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(9)->addWork(f_10_OiOLCPqsuG);
		auto f_11_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 18587; INDEX_OiOLCPqsuG < 18587 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(10)->addWork(f_11_OiOLCPqsuG);
		auto f_12_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 20445; INDEX_OiOLCPqsuG < 20445 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(11)->addWork(f_12_OiOLCPqsuG);
		auto f_13_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 22303; INDEX_OiOLCPqsuG < 22303 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(12)->addWork(f_13_OiOLCPqsuG);
		auto f_14_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 24161; INDEX_OiOLCPqsuG < 24161 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(13)->addWork(f_14_OiOLCPqsuG);
		auto f_15_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 26019; INDEX_OiOLCPqsuG < 26019 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(14)->addWork(f_15_OiOLCPqsuG);
		auto f_16_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 27877; INDEX_OiOLCPqsuG < 27877 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(15)->addWork(f_16_OiOLCPqsuG);
		auto f_17_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 29735; INDEX_OiOLCPqsuG < 29735 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(16)->addWork(f_17_OiOLCPqsuG);
		auto f_18_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 31593; INDEX_OiOLCPqsuG < 31593 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(17)->addWork(f_18_OiOLCPqsuG);
		auto f_19_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 33451; INDEX_OiOLCPqsuG < 33451 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(18)->addWork(f_19_OiOLCPqsuG);
		auto f_20_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 35309; INDEX_OiOLCPqsuG < 35309 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(19)->addWork(f_20_OiOLCPqsuG);
		auto f_21_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 37167; INDEX_OiOLCPqsuG < 37167 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(20)->addWork(f_21_OiOLCPqsuG);
		auto f_22_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 39025; INDEX_OiOLCPqsuG < 39025 + 1858; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(21)->addWork(f_22_OiOLCPqsuG);
		auto f_23_OiOLCPqsuG = [&] () {
			for (size_t INDEX_OiOLCPqsuG = 40883; INDEX_OiOLCPqsuG < 40883 + 1881; ++INDEX_OiOLCPqsuG) {
				dists_6eG7OrYJh4[(INDEX_OiOLCPqsuG)] = sqrt((lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_OiOLCPqsuG)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_OiOLCPqsuG)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(22)->addWork(f_23_OiOLCPqsuG);
	}
	if (rank == 0) {
		ii_VlRUFPD0ob_cPQC8UBv5p++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_ahoJZc947T = new Bit_Mask(47,true);
		for (size_t i_Y3gRPCUVbj = 0; i_Y3gRPCUVbj < 23; ++i_Y3gRPCUVbj) {
			mask_ptr_ahoJZc947T->setBarrier(i_Y3gRPCUVbj);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_ahoJZc947T (mask_ptr_ahoJZc947T);
		self_barrier(boost_mask_ptr_ahoJZc947T);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8tDNhYDxsV[(j)] > max_val) {
					max_val = neighbor_dist_8tDNhYDxsV[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_6eG7OrYJh4[(i)]) {
				neighbor_dist_8tDNhYDxsV[(max_id)] = dists_6eG7OrYJh4[(i)];
				neighbor_id_IHC0dMJpg6[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[0] = get_time() - time[0];
if ((ii_VlRUFPD0ob_cPQC8UBv5p == 0)) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 1) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 2) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[1] = get_time();
auto f_1_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 0; INDEX_qy0ze1d6sb < 0 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(0)->addWork(f_1_qy0ze1d6sb);
		auto f_2_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 1859; INDEX_qy0ze1d6sb < 1859 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(1)->addWork(f_2_qy0ze1d6sb);
		auto f_3_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 3718; INDEX_qy0ze1d6sb < 3718 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(2)->addWork(f_3_qy0ze1d6sb);
		auto f_4_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 5577; INDEX_qy0ze1d6sb < 5577 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(3)->addWork(f_4_qy0ze1d6sb);
		auto f_5_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 7436; INDEX_qy0ze1d6sb < 7436 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(4)->addWork(f_5_qy0ze1d6sb);
		auto f_6_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 9295; INDEX_qy0ze1d6sb < 9295 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(5)->addWork(f_6_qy0ze1d6sb);
		auto f_7_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 11154; INDEX_qy0ze1d6sb < 11154 + 1859; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(6)->addWork(f_7_qy0ze1d6sb);
		auto f_8_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 13013; INDEX_qy0ze1d6sb < 13013 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(7)->addWork(f_8_qy0ze1d6sb);
		auto f_9_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 14871; INDEX_qy0ze1d6sb < 14871 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(8)->addWork(f_9_qy0ze1d6sb);
		auto f_10_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 16729; INDEX_qy0ze1d6sb < 16729 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(9)->addWork(f_10_qy0ze1d6sb);
		auto f_11_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 18587; INDEX_qy0ze1d6sb < 18587 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(10)->addWork(f_11_qy0ze1d6sb);
		auto f_12_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 20445; INDEX_qy0ze1d6sb < 20445 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(11)->addWork(f_12_qy0ze1d6sb);
		auto f_13_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 22303; INDEX_qy0ze1d6sb < 22303 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(12)->addWork(f_13_qy0ze1d6sb);
		auto f_14_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 24161; INDEX_qy0ze1d6sb < 24161 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(13)->addWork(f_14_qy0ze1d6sb);
		auto f_15_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 26019; INDEX_qy0ze1d6sb < 26019 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(14)->addWork(f_15_qy0ze1d6sb);
		auto f_16_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 27877; INDEX_qy0ze1d6sb < 27877 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(15)->addWork(f_16_qy0ze1d6sb);
		auto f_17_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 29735; INDEX_qy0ze1d6sb < 29735 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(16)->addWork(f_17_qy0ze1d6sb);
		auto f_18_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 31593; INDEX_qy0ze1d6sb < 31593 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(17)->addWork(f_18_qy0ze1d6sb);
		auto f_19_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 33451; INDEX_qy0ze1d6sb < 33451 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(18)->addWork(f_19_qy0ze1d6sb);
		auto f_20_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 35309; INDEX_qy0ze1d6sb < 35309 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(19)->addWork(f_20_qy0ze1d6sb);
		auto f_21_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 37167; INDEX_qy0ze1d6sb < 37167 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(20)->addWork(f_21_qy0ze1d6sb);
		auto f_22_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 39025; INDEX_qy0ze1d6sb < 39025 + 1858; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(21)->addWork(f_22_qy0ze1d6sb);
		auto f_23_qy0ze1d6sb = [&] () {
			for (size_t INDEX_qy0ze1d6sb = 40883; INDEX_qy0ze1d6sb < 40883 + 1881; ++INDEX_qy0ze1d6sb) {
				dists_6eG7OrYJh4[(INDEX_qy0ze1d6sb)] = sqrt((lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_qy0ze1d6sb)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_qy0ze1d6sb)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(22)->addWork(f_23_qy0ze1d6sb);
	}
	if (rank == 0) {
		ii_VlRUFPD0ob_cPQC8UBv5p++;
	}
	if (rank == 0) {
		time[1] = get_time() - time[1];
if ((ii_VlRUFPD0ob_cPQC8UBv5p == 0)) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 1) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 2) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_QNPFuEsct1 = new Bit_Mask(47,true);
		for (size_t i_oExHIfguNO = 0; i_oExHIfguNO < 23; ++i_oExHIfguNO) {
			mask_ptr_QNPFuEsct1->setBarrier(i_oExHIfguNO);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_QNPFuEsct1 (mask_ptr_QNPFuEsct1);
		self_barrier(boost_mask_ptr_QNPFuEsct1);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8tDNhYDxsV[(j)] > max_val) {
					max_val = neighbor_dist_8tDNhYDxsV[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_6eG7OrYJh4[(i)]) {
				neighbor_dist_8tDNhYDxsV[(max_id)] = dists_6eG7OrYJh4[(i)];
				neighbor_id_IHC0dMJpg6[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time();
auto f_1_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 0; INDEX_DF6aAjX5Rq < 0 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(0)->addWork(f_1_DF6aAjX5Rq);
		auto f_2_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 1859; INDEX_DF6aAjX5Rq < 1859 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(1)->addWork(f_2_DF6aAjX5Rq);
		auto f_3_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 3718; INDEX_DF6aAjX5Rq < 3718 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(2)->addWork(f_3_DF6aAjX5Rq);
		auto f_4_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 5577; INDEX_DF6aAjX5Rq < 5577 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(3)->addWork(f_4_DF6aAjX5Rq);
		auto f_5_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 7436; INDEX_DF6aAjX5Rq < 7436 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(4)->addWork(f_5_DF6aAjX5Rq);
		auto f_6_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 9295; INDEX_DF6aAjX5Rq < 9295 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(5)->addWork(f_6_DF6aAjX5Rq);
		auto f_7_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 11154; INDEX_DF6aAjX5Rq < 11154 + 1859; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(6)->addWork(f_7_DF6aAjX5Rq);
		auto f_8_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 13013; INDEX_DF6aAjX5Rq < 13013 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(7)->addWork(f_8_DF6aAjX5Rq);
		auto f_9_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 14871; INDEX_DF6aAjX5Rq < 14871 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(8)->addWork(f_9_DF6aAjX5Rq);
		auto f_10_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 16729; INDEX_DF6aAjX5Rq < 16729 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(9)->addWork(f_10_DF6aAjX5Rq);
		auto f_11_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 18587; INDEX_DF6aAjX5Rq < 18587 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(10)->addWork(f_11_DF6aAjX5Rq);
		auto f_12_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 20445; INDEX_DF6aAjX5Rq < 20445 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(11)->addWork(f_12_DF6aAjX5Rq);
		auto f_13_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 22303; INDEX_DF6aAjX5Rq < 22303 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(12)->addWork(f_13_DF6aAjX5Rq);
		auto f_14_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 24161; INDEX_DF6aAjX5Rq < 24161 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(13)->addWork(f_14_DF6aAjX5Rq);
		auto f_15_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 26019; INDEX_DF6aAjX5Rq < 26019 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(14)->addWork(f_15_DF6aAjX5Rq);
		auto f_16_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 27877; INDEX_DF6aAjX5Rq < 27877 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(15)->addWork(f_16_DF6aAjX5Rq);
		auto f_17_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 29735; INDEX_DF6aAjX5Rq < 29735 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(16)->addWork(f_17_DF6aAjX5Rq);
		auto f_18_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 31593; INDEX_DF6aAjX5Rq < 31593 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(17)->addWork(f_18_DF6aAjX5Rq);
		auto f_19_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 33451; INDEX_DF6aAjX5Rq < 33451 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(18)->addWork(f_19_DF6aAjX5Rq);
		auto f_20_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 35309; INDEX_DF6aAjX5Rq < 35309 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(19)->addWork(f_20_DF6aAjX5Rq);
		auto f_21_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 37167; INDEX_DF6aAjX5Rq < 37167 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(20)->addWork(f_21_DF6aAjX5Rq);
		auto f_22_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 39025; INDEX_DF6aAjX5Rq < 39025 + 1858; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(21)->addWork(f_22_DF6aAjX5Rq);
		auto f_23_DF6aAjX5Rq = [&] () {
			for (size_t INDEX_DF6aAjX5Rq = 40883; INDEX_DF6aAjX5Rq < 40883 + 1881; ++INDEX_DF6aAjX5Rq) {
				dists_6eG7OrYJh4[(INDEX_DF6aAjX5Rq)] = sqrt((lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_DF6aAjX5Rq)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_DF6aAjX5Rq)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(22)->addWork(f_23_DF6aAjX5Rq);
	}
	if (rank == 0) {
		ii_VlRUFPD0ob_cPQC8UBv5p++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_Wy9PGpZ4pj = new Bit_Mask(47,true);
		for (size_t i_hLUbfKRAoX = 0; i_hLUbfKRAoX < 23; ++i_hLUbfKRAoX) {
			mask_ptr_Wy9PGpZ4pj->setBarrier(i_hLUbfKRAoX);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_Wy9PGpZ4pj (mask_ptr_Wy9PGpZ4pj);
		self_barrier(boost_mask_ptr_Wy9PGpZ4pj);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8tDNhYDxsV[(j)] > max_val) {
					max_val = neighbor_dist_8tDNhYDxsV[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_6eG7OrYJh4[(i)]) {
				neighbor_dist_8tDNhYDxsV[(max_id)] = dists_6eG7OrYJh4[(i)];
				neighbor_id_IHC0dMJpg6[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time() - time[2];
if ((ii_VlRUFPD0ob_cPQC8UBv5p == 0)) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 1) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_VlRUFPD0ob_cPQC8UBv5p == 2) {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_MQs82k9kZP, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_ouEE9yLRax, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[3] = get_time();
auto f_1_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 0; INDEX_t9TfXhB1Sf < 0 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(0)->addWork(f_1_t9TfXhB1Sf);
		auto f_2_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 1859; INDEX_t9TfXhB1Sf < 1859 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(1)->addWork(f_2_t9TfXhB1Sf);
		auto f_3_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 3718; INDEX_t9TfXhB1Sf < 3718 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(2)->addWork(f_3_t9TfXhB1Sf);
		auto f_4_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 5577; INDEX_t9TfXhB1Sf < 5577 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(3)->addWork(f_4_t9TfXhB1Sf);
		auto f_5_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 7436; INDEX_t9TfXhB1Sf < 7436 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(4)->addWork(f_5_t9TfXhB1Sf);
		auto f_6_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 9295; INDEX_t9TfXhB1Sf < 9295 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(5)->addWork(f_6_t9TfXhB1Sf);
		auto f_7_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 11154; INDEX_t9TfXhB1Sf < 11154 + 1859; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(6)->addWork(f_7_t9TfXhB1Sf);
		auto f_8_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 13013; INDEX_t9TfXhB1Sf < 13013 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(7)->addWork(f_8_t9TfXhB1Sf);
		auto f_9_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 14871; INDEX_t9TfXhB1Sf < 14871 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(8)->addWork(f_9_t9TfXhB1Sf);
		auto f_10_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 16729; INDEX_t9TfXhB1Sf < 16729 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(9)->addWork(f_10_t9TfXhB1Sf);
		auto f_11_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 18587; INDEX_t9TfXhB1Sf < 18587 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(10)->addWork(f_11_t9TfXhB1Sf);
		auto f_12_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 20445; INDEX_t9TfXhB1Sf < 20445 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(11)->addWork(f_12_t9TfXhB1Sf);
		auto f_13_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 22303; INDEX_t9TfXhB1Sf < 22303 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(12)->addWork(f_13_t9TfXhB1Sf);
		auto f_14_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 24161; INDEX_t9TfXhB1Sf < 24161 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(13)->addWork(f_14_t9TfXhB1Sf);
		auto f_15_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 26019; INDEX_t9TfXhB1Sf < 26019 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(14)->addWork(f_15_t9TfXhB1Sf);
		auto f_16_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 27877; INDEX_t9TfXhB1Sf < 27877 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(15)->addWork(f_16_t9TfXhB1Sf);
		auto f_17_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 29735; INDEX_t9TfXhB1Sf < 29735 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(16)->addWork(f_17_t9TfXhB1Sf);
		auto f_18_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 31593; INDEX_t9TfXhB1Sf < 31593 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(17)->addWork(f_18_t9TfXhB1Sf);
		auto f_19_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 33451; INDEX_t9TfXhB1Sf < 33451 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(18)->addWork(f_19_t9TfXhB1Sf);
		auto f_20_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 35309; INDEX_t9TfXhB1Sf < 35309 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(19)->addWork(f_20_t9TfXhB1Sf);
		auto f_21_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 37167; INDEX_t9TfXhB1Sf < 37167 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(20)->addWork(f_21_t9TfXhB1Sf);
		auto f_22_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 39025; INDEX_t9TfXhB1Sf < 39025 + 1858; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(21)->addWork(f_22_t9TfXhB1Sf);
		auto f_23_t9TfXhB1Sf = [&] () {
			for (size_t INDEX_t9TfXhB1Sf = 40883; INDEX_t9TfXhB1Sf < 40883 + 1881; ++INDEX_t9TfXhB1Sf) {
				dists_6eG7OrYJh4[(INDEX_t9TfXhB1Sf)] = sqrt((lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) * (lon_MQs82k9kZP[(INDEX_t9TfXhB1Sf)] - target_lon_bga9uhfoWF) + (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx) * (lat_ouEE9yLRax[(INDEX_t9TfXhB1Sf)] - target_lat_bcOh37UIZx));
			}
		};
		getPool()->at(22)->addWork(f_23_t9TfXhB1Sf);
	}
	if (rank == 0) {
		ii_VlRUFPD0ob_cPQC8UBv5p++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_e4gztUksyQ = new Bit_Mask(47,true);
		for (size_t i_X14IdKLJmV = 0; i_X14IdKLJmV < 23; ++i_X14IdKLJmV) {
			mask_ptr_e4gztUksyQ->setBarrier(i_X14IdKLJmV);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_e4gztUksyQ (mask_ptr_e4gztUksyQ);
		self_barrier(boost_mask_ptr_e4gztUksyQ);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8tDNhYDxsV[(j)] > max_val) {
					max_val = neighbor_dist_8tDNhYDxsV[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_6eG7OrYJh4[(i)]) {
				neighbor_dist_8tDNhYDxsV[(max_id)] = dists_6eG7OrYJh4[(i)];
				neighbor_id_IHC0dMJpg6[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_8tDNhYDxsV, 1LL * 5);
		array_write("canes.txt", neighbor_id_IHC0dMJpg6, 1LL * 5);
	}
	finishExecution();
	finishGPUExecution();
	std::free(lon_MQs82k9kZP);
	std::free(neighbor_dist_8tDNhYDxsV);
	std::free(times_FTDz3FHJPz);
	std::free(neighbor_id_IHC0dMJpg6);
	std::free(lat_ouEE9yLRax);
	std::free(dists_6eG7OrYJh4);
	MPI_Finalize();
	return 0;


}

