
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef nn_HXX
#define nn_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

    float tanh_taylor(float x);


#endif