/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_g_2.hxx"
#include "includes/cuda_lib_nn_g_2.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	int32_t ii_UaNOgzFEvg_B2eA8axtHu;
	float* lon_1kaf55xYIV;
	float* neighbor_dist_8Xib6v9gvx;
	int64_t* times_pFzBY1CBe3;
	int32_t* neighbor_id_EvsmNVWVuj;
	float target_lat_LM1RYciLkY;
	float target_lon_rlNESevb37;
	float* lat_oaRfasmc3e;
	float* dists_87VBWeuC10;
	int NUM_CORES;
	int NUM_GPUS;

	int rank, nprocs;
	MPI_Status Stat;
	MPI_Init(&argc, &argv);
	MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank);
	if (rank == 0 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	} else 	if (rank == 1 ) {
		NUM_CORES = 47;
		NUM_GPUS = 0;
	}
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_8Xib6v9gvx = Init_List(100000, neighbor_dist_8Xib6v9gvx, 5LL * 1LL);
	dists_87VBWeuC10 = Init_List(dists_87VBWeuC10, 42764LL * 1LL);
	lon_1kaf55xYIV = Init_List(lon_1kaf55xYIV, 42764LL * 1LL);
	neighbor_id_EvsmNVWVuj = Init_List(neighbor_id_EvsmNVWVuj, 5LL * 1LL);
	times_pFzBY1CBe3 = Init_List(times_pFzBY1CBe3, 4LL * 1LL);
	lat_oaRfasmc3e = Init_List(lat_oaRfasmc3e, 42764LL * 1LL);
	if (rank == 0) {
		ii_UaNOgzFEvg_B2eA8axtHu = 0;
	}
	if (rank == 0) {
		target_lon_rlNESevb37 = 90;
		target_lat_LM1RYciLkY = 30;
	}
	if (rank == 0) {
		
if ((ii_UaNOgzFEvg_B2eA8axtHu == 0)) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 1) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 2) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[0] = get_time();
auto f_1_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 0; INDEX_FP81uqLbYG < 0 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(0)->addWork(f_1_FP81uqLbYG);
		auto f_2_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 1859; INDEX_FP81uqLbYG < 1859 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(1)->addWork(f_2_FP81uqLbYG);
		auto f_3_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 3718; INDEX_FP81uqLbYG < 3718 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(2)->addWork(f_3_FP81uqLbYG);
		auto f_4_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 5577; INDEX_FP81uqLbYG < 5577 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(3)->addWork(f_4_FP81uqLbYG);
		auto f_5_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 7436; INDEX_FP81uqLbYG < 7436 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(4)->addWork(f_5_FP81uqLbYG);
		auto f_6_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 9295; INDEX_FP81uqLbYG < 9295 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(5)->addWork(f_6_FP81uqLbYG);
		auto f_7_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 11154; INDEX_FP81uqLbYG < 11154 + 1859; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(6)->addWork(f_7_FP81uqLbYG);
		auto f_8_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 13013; INDEX_FP81uqLbYG < 13013 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(7)->addWork(f_8_FP81uqLbYG);
		auto f_9_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 14871; INDEX_FP81uqLbYG < 14871 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(8)->addWork(f_9_FP81uqLbYG);
		auto f_10_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 16729; INDEX_FP81uqLbYG < 16729 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(9)->addWork(f_10_FP81uqLbYG);
		auto f_11_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 18587; INDEX_FP81uqLbYG < 18587 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(10)->addWork(f_11_FP81uqLbYG);
		auto f_12_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 20445; INDEX_FP81uqLbYG < 20445 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(11)->addWork(f_12_FP81uqLbYG);
		auto f_13_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 22303; INDEX_FP81uqLbYG < 22303 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(12)->addWork(f_13_FP81uqLbYG);
		auto f_14_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 24161; INDEX_FP81uqLbYG < 24161 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(13)->addWork(f_14_FP81uqLbYG);
		auto f_15_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 26019; INDEX_FP81uqLbYG < 26019 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(14)->addWork(f_15_FP81uqLbYG);
		auto f_16_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 27877; INDEX_FP81uqLbYG < 27877 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(15)->addWork(f_16_FP81uqLbYG);
		auto f_17_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 29735; INDEX_FP81uqLbYG < 29735 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(16)->addWork(f_17_FP81uqLbYG);
		auto f_18_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 31593; INDEX_FP81uqLbYG < 31593 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(17)->addWork(f_18_FP81uqLbYG);
		auto f_19_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 33451; INDEX_FP81uqLbYG < 33451 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(18)->addWork(f_19_FP81uqLbYG);
		auto f_20_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 35309; INDEX_FP81uqLbYG < 35309 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(19)->addWork(f_20_FP81uqLbYG);
		auto f_21_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 37167; INDEX_FP81uqLbYG < 37167 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(20)->addWork(f_21_FP81uqLbYG);
		auto f_22_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 39025; INDEX_FP81uqLbYG < 39025 + 1858; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(21)->addWork(f_22_FP81uqLbYG);
		auto f_23_FP81uqLbYG = [&] () {
			for (size_t INDEX_FP81uqLbYG = 40883; INDEX_FP81uqLbYG < 40883 + 1881; ++INDEX_FP81uqLbYG) {
				dists_87VBWeuC10[(INDEX_FP81uqLbYG)] = sqrt((lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_FP81uqLbYG)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_FP81uqLbYG)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(22)->addWork(f_23_FP81uqLbYG);
	}
	if (rank == 0) {
		ii_UaNOgzFEvg_B2eA8axtHu++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_1aV2RtTdWb = new Bit_Mask(47,true);
		for (size_t i_9d249OQURR = 0; i_9d249OQURR < 23; ++i_9d249OQURR) {
			mask_ptr_1aV2RtTdWb->setBarrier(i_9d249OQURR);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_1aV2RtTdWb (mask_ptr_1aV2RtTdWb);
		self_barrier(boost_mask_ptr_1aV2RtTdWb);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8Xib6v9gvx[(j)] > max_val) {
					max_val = neighbor_dist_8Xib6v9gvx[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_87VBWeuC10[(i)]) {
				neighbor_dist_8Xib6v9gvx[(max_id)] = dists_87VBWeuC10[(i)];
				neighbor_id_EvsmNVWVuj[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[0] = get_time() - time[0];
if ((ii_UaNOgzFEvg_B2eA8axtHu == 0)) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 1) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 2) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[1] = get_time();
auto f_1_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 0; INDEX_VcI8dgp5Mp < 0 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(0)->addWork(f_1_VcI8dgp5Mp);
		auto f_2_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 1859; INDEX_VcI8dgp5Mp < 1859 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(1)->addWork(f_2_VcI8dgp5Mp);
		auto f_3_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 3718; INDEX_VcI8dgp5Mp < 3718 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(2)->addWork(f_3_VcI8dgp5Mp);
		auto f_4_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 5577; INDEX_VcI8dgp5Mp < 5577 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(3)->addWork(f_4_VcI8dgp5Mp);
		auto f_5_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 7436; INDEX_VcI8dgp5Mp < 7436 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(4)->addWork(f_5_VcI8dgp5Mp);
		auto f_6_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 9295; INDEX_VcI8dgp5Mp < 9295 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(5)->addWork(f_6_VcI8dgp5Mp);
		auto f_7_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 11154; INDEX_VcI8dgp5Mp < 11154 + 1859; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(6)->addWork(f_7_VcI8dgp5Mp);
		auto f_8_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 13013; INDEX_VcI8dgp5Mp < 13013 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(7)->addWork(f_8_VcI8dgp5Mp);
		auto f_9_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 14871; INDEX_VcI8dgp5Mp < 14871 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(8)->addWork(f_9_VcI8dgp5Mp);
		auto f_10_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 16729; INDEX_VcI8dgp5Mp < 16729 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(9)->addWork(f_10_VcI8dgp5Mp);
		auto f_11_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 18587; INDEX_VcI8dgp5Mp < 18587 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(10)->addWork(f_11_VcI8dgp5Mp);
		auto f_12_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 20445; INDEX_VcI8dgp5Mp < 20445 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(11)->addWork(f_12_VcI8dgp5Mp);
		auto f_13_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 22303; INDEX_VcI8dgp5Mp < 22303 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(12)->addWork(f_13_VcI8dgp5Mp);
		auto f_14_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 24161; INDEX_VcI8dgp5Mp < 24161 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(13)->addWork(f_14_VcI8dgp5Mp);
		auto f_15_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 26019; INDEX_VcI8dgp5Mp < 26019 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(14)->addWork(f_15_VcI8dgp5Mp);
		auto f_16_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 27877; INDEX_VcI8dgp5Mp < 27877 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(15)->addWork(f_16_VcI8dgp5Mp);
		auto f_17_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 29735; INDEX_VcI8dgp5Mp < 29735 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(16)->addWork(f_17_VcI8dgp5Mp);
		auto f_18_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 31593; INDEX_VcI8dgp5Mp < 31593 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(17)->addWork(f_18_VcI8dgp5Mp);
		auto f_19_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 33451; INDEX_VcI8dgp5Mp < 33451 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(18)->addWork(f_19_VcI8dgp5Mp);
		auto f_20_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 35309; INDEX_VcI8dgp5Mp < 35309 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(19)->addWork(f_20_VcI8dgp5Mp);
		auto f_21_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 37167; INDEX_VcI8dgp5Mp < 37167 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(20)->addWork(f_21_VcI8dgp5Mp);
		auto f_22_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 39025; INDEX_VcI8dgp5Mp < 39025 + 1858; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(21)->addWork(f_22_VcI8dgp5Mp);
		auto f_23_VcI8dgp5Mp = [&] () {
			for (size_t INDEX_VcI8dgp5Mp = 40883; INDEX_VcI8dgp5Mp < 40883 + 1881; ++INDEX_VcI8dgp5Mp) {
				dists_87VBWeuC10[(INDEX_VcI8dgp5Mp)] = sqrt((lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_VcI8dgp5Mp)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_VcI8dgp5Mp)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(22)->addWork(f_23_VcI8dgp5Mp);
	}
	if (rank == 0) {
		ii_UaNOgzFEvg_B2eA8axtHu++;
	}
	if (rank == 0) {
		time[1] = get_time() - time[1];
if ((ii_UaNOgzFEvg_B2eA8axtHu == 0)) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 1) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 2) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_g2CbohIr5r = new Bit_Mask(47,true);
		for (size_t i_Ml4JALjp5I = 0; i_Ml4JALjp5I < 23; ++i_Ml4JALjp5I) {
			mask_ptr_g2CbohIr5r->setBarrier(i_Ml4JALjp5I);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_g2CbohIr5r (mask_ptr_g2CbohIr5r);
		self_barrier(boost_mask_ptr_g2CbohIr5r);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8Xib6v9gvx[(j)] > max_val) {
					max_val = neighbor_dist_8Xib6v9gvx[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_87VBWeuC10[(i)]) {
				neighbor_dist_8Xib6v9gvx[(max_id)] = dists_87VBWeuC10[(i)];
				neighbor_id_EvsmNVWVuj[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time();
auto f_1_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 0; INDEX_sHWpF4LWXa < 0 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(0)->addWork(f_1_sHWpF4LWXa);
		auto f_2_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 1859; INDEX_sHWpF4LWXa < 1859 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(1)->addWork(f_2_sHWpF4LWXa);
		auto f_3_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 3718; INDEX_sHWpF4LWXa < 3718 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(2)->addWork(f_3_sHWpF4LWXa);
		auto f_4_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 5577; INDEX_sHWpF4LWXa < 5577 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(3)->addWork(f_4_sHWpF4LWXa);
		auto f_5_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 7436; INDEX_sHWpF4LWXa < 7436 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(4)->addWork(f_5_sHWpF4LWXa);
		auto f_6_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 9295; INDEX_sHWpF4LWXa < 9295 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(5)->addWork(f_6_sHWpF4LWXa);
		auto f_7_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 11154; INDEX_sHWpF4LWXa < 11154 + 1859; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(6)->addWork(f_7_sHWpF4LWXa);
		auto f_8_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 13013; INDEX_sHWpF4LWXa < 13013 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(7)->addWork(f_8_sHWpF4LWXa);
		auto f_9_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 14871; INDEX_sHWpF4LWXa < 14871 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(8)->addWork(f_9_sHWpF4LWXa);
		auto f_10_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 16729; INDEX_sHWpF4LWXa < 16729 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(9)->addWork(f_10_sHWpF4LWXa);
		auto f_11_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 18587; INDEX_sHWpF4LWXa < 18587 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(10)->addWork(f_11_sHWpF4LWXa);
		auto f_12_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 20445; INDEX_sHWpF4LWXa < 20445 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(11)->addWork(f_12_sHWpF4LWXa);
		auto f_13_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 22303; INDEX_sHWpF4LWXa < 22303 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(12)->addWork(f_13_sHWpF4LWXa);
		auto f_14_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 24161; INDEX_sHWpF4LWXa < 24161 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(13)->addWork(f_14_sHWpF4LWXa);
		auto f_15_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 26019; INDEX_sHWpF4LWXa < 26019 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(14)->addWork(f_15_sHWpF4LWXa);
		auto f_16_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 27877; INDEX_sHWpF4LWXa < 27877 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(15)->addWork(f_16_sHWpF4LWXa);
		auto f_17_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 29735; INDEX_sHWpF4LWXa < 29735 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(16)->addWork(f_17_sHWpF4LWXa);
		auto f_18_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 31593; INDEX_sHWpF4LWXa < 31593 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(17)->addWork(f_18_sHWpF4LWXa);
		auto f_19_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 33451; INDEX_sHWpF4LWXa < 33451 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(18)->addWork(f_19_sHWpF4LWXa);
		auto f_20_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 35309; INDEX_sHWpF4LWXa < 35309 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(19)->addWork(f_20_sHWpF4LWXa);
		auto f_21_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 37167; INDEX_sHWpF4LWXa < 37167 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(20)->addWork(f_21_sHWpF4LWXa);
		auto f_22_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 39025; INDEX_sHWpF4LWXa < 39025 + 1858; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(21)->addWork(f_22_sHWpF4LWXa);
		auto f_23_sHWpF4LWXa = [&] () {
			for (size_t INDEX_sHWpF4LWXa = 40883; INDEX_sHWpF4LWXa < 40883 + 1881; ++INDEX_sHWpF4LWXa) {
				dists_87VBWeuC10[(INDEX_sHWpF4LWXa)] = sqrt((lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_sHWpF4LWXa)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_sHWpF4LWXa)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(22)->addWork(f_23_sHWpF4LWXa);
	}
	if (rank == 0) {
		ii_UaNOgzFEvg_B2eA8axtHu++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_fZY1PT8K3e = new Bit_Mask(47,true);
		for (size_t i_gya0l3A8bk = 0; i_gya0l3A8bk < 23; ++i_gya0l3A8bk) {
			mask_ptr_fZY1PT8K3e->setBarrier(i_gya0l3A8bk);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_fZY1PT8K3e (mask_ptr_fZY1PT8K3e);
		self_barrier(boost_mask_ptr_fZY1PT8K3e);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8Xib6v9gvx[(j)] > max_val) {
					max_val = neighbor_dist_8Xib6v9gvx[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_87VBWeuC10[(i)]) {
				neighbor_dist_8Xib6v9gvx[(max_id)] = dists_87VBWeuC10[(i)];
				neighbor_id_EvsmNVWVuj[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[2] = get_time() - time[2];
if ((ii_UaNOgzFEvg_B2eA8axtHu == 0)) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 1) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else 		if (ii_UaNOgzFEvg_B2eA8axtHu == 2) {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		} else {
			Set_Partial_Array(lon_1kaf55xYIV, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
			Set_Partial_Array(lat_oaRfasmc3e, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		}
	}
	if (rank == 0) {
		time[3] = get_time();
auto f_1_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 0; INDEX_Wan1urL97v < 0 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(0)->addWork(f_1_Wan1urL97v);
		auto f_2_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 1859; INDEX_Wan1urL97v < 1859 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(1)->addWork(f_2_Wan1urL97v);
		auto f_3_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 3718; INDEX_Wan1urL97v < 3718 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(2)->addWork(f_3_Wan1urL97v);
		auto f_4_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 5577; INDEX_Wan1urL97v < 5577 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(3)->addWork(f_4_Wan1urL97v);
		auto f_5_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 7436; INDEX_Wan1urL97v < 7436 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(4)->addWork(f_5_Wan1urL97v);
		auto f_6_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 9295; INDEX_Wan1urL97v < 9295 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(5)->addWork(f_6_Wan1urL97v);
		auto f_7_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 11154; INDEX_Wan1urL97v < 11154 + 1859; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(6)->addWork(f_7_Wan1urL97v);
		auto f_8_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 13013; INDEX_Wan1urL97v < 13013 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(7)->addWork(f_8_Wan1urL97v);
		auto f_9_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 14871; INDEX_Wan1urL97v < 14871 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(8)->addWork(f_9_Wan1urL97v);
		auto f_10_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 16729; INDEX_Wan1urL97v < 16729 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(9)->addWork(f_10_Wan1urL97v);
		auto f_11_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 18587; INDEX_Wan1urL97v < 18587 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(10)->addWork(f_11_Wan1urL97v);
		auto f_12_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 20445; INDEX_Wan1urL97v < 20445 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(11)->addWork(f_12_Wan1urL97v);
		auto f_13_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 22303; INDEX_Wan1urL97v < 22303 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(12)->addWork(f_13_Wan1urL97v);
		auto f_14_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 24161; INDEX_Wan1urL97v < 24161 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(13)->addWork(f_14_Wan1urL97v);
		auto f_15_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 26019; INDEX_Wan1urL97v < 26019 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(14)->addWork(f_15_Wan1urL97v);
		auto f_16_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 27877; INDEX_Wan1urL97v < 27877 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(15)->addWork(f_16_Wan1urL97v);
		auto f_17_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 29735; INDEX_Wan1urL97v < 29735 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(16)->addWork(f_17_Wan1urL97v);
		auto f_18_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 31593; INDEX_Wan1urL97v < 31593 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(17)->addWork(f_18_Wan1urL97v);
		auto f_19_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 33451; INDEX_Wan1urL97v < 33451 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(18)->addWork(f_19_Wan1urL97v);
		auto f_20_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 35309; INDEX_Wan1urL97v < 35309 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(19)->addWork(f_20_Wan1urL97v);
		auto f_21_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 37167; INDEX_Wan1urL97v < 37167 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(20)->addWork(f_21_Wan1urL97v);
		auto f_22_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 39025; INDEX_Wan1urL97v < 39025 + 1858; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(21)->addWork(f_22_Wan1urL97v);
		auto f_23_Wan1urL97v = [&] () {
			for (size_t INDEX_Wan1urL97v = 40883; INDEX_Wan1urL97v < 40883 + 1881; ++INDEX_Wan1urL97v) {
				dists_87VBWeuC10[(INDEX_Wan1urL97v)] = sqrt((lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) * (lon_1kaf55xYIV[(INDEX_Wan1urL97v)] - target_lon_rlNESevb37) + (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY) * (lat_oaRfasmc3e[(INDEX_Wan1urL97v)] - target_lat_LM1RYciLkY));
			}
		};
		getPool()->at(22)->addWork(f_23_Wan1urL97v);
	}
	if (rank == 0) {
		ii_UaNOgzFEvg_B2eA8axtHu++;
	}
	if (rank == 0) {
		Bit_Mask * mask_ptr_1IeIka60ut = new Bit_Mask(47,true);
		for (size_t i_ovE3C393el = 0; i_ovE3C393el < 23; ++i_ovE3C393el) {
			mask_ptr_1IeIka60ut->setBarrier(i_ovE3C393el);
		}
		boost::shared_ptr<Bit_Mask>boost_mask_ptr_1IeIka60ut (mask_ptr_1IeIka60ut);
		self_barrier(boost_mask_ptr_1IeIka60ut);
	}
	if (rank == 0) {
		for ( int32_t i = 0; i < 42764; i++ ) {
			float max_val;
			int32_t max_id;
			max_id = 0;
			max_val = 0 - 1;
			for ( int32_t j = 0; j < 5; j++ ) {
				if (neighbor_dist_8Xib6v9gvx[(j)] > max_val) {
					max_val = neighbor_dist_8Xib6v9gvx[(j)];
					max_id = j;
				}
			}
			if (max_val > dists_87VBWeuC10[(i)]) {
				neighbor_dist_8Xib6v9gvx[(max_id)] = dists_87VBWeuC10[(i)];
				neighbor_id_EvsmNVWVuj[(max_id)] = i;
			}
		}
	}
	if (rank == 0) {
		time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_8Xib6v9gvx, 1LL * 5);
		array_write("canes.txt", neighbor_id_EvsmNVWVuj, 1LL * 5);
	}
	finishExecution();
	finishGPUExecution();
	std::free(lon_1kaf55xYIV);
	std::free(neighbor_dist_8Xib6v9gvx);
	std::free(times_pFzBY1CBe3);
	std::free(neighbor_id_EvsmNVWVuj);
	std::free(lat_oaRfasmc3e);
	std::free(dists_87VBWeuC10);
	MPI_Finalize();
	return 0;


}

