
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef backprop_g_2_HXX
#define backprop_g_2_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

    float squash(float x);


#endif