
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef LavaMD_m_1_HXX
#define LavaMD_m_1_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

    float* force_combination(float* rv_home, float* rv_neighbor, float* qv_neighbor);


#endif