
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef srad_g_2_HXX
#define srad_g_2_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

    float get_cS(float* c, int32_t i, int32_t j);
    float get_cE(float* c, int32_t i, int32_t j);


#endif