/*********************************************************************/
/*        This is a generated C++ source file.                       */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/

#include <vector>
#include <cstdint>
#include <string>
#include <limits>
#include <iostream>
#include "includes/Patternlib.hxx"
#include "includes/PThreadsLib.hxx"
#include "includes/nn_g_1.hxx"
#include "includes/cuda_lib_nn_g_1.hxx"
#include "mpi.h"
#include "includes/cuda_pool_lib.hxx"
#include "math.h"




/*********************************************************************/
/*        Global Variables                                           */
/*        Generated by PatternDSL .                                  */
/*********************************************************************/



/*********************************************************************/
/*        Function Declarations                                      */
/*        Generated by PatternDSL.                                   */
/*********************************************************************/



int main(int argc, char** argv) {
long long time[4];

	int32_t ii_m0W5Go1hvm_QMDA3CFZtp;
	float* lon_eOLMuPEYrA;
	float* neighbor_dist_BOG4iSodlN;
	int64_t* times_UZT91L6oCj;
	int32_t* neighbor_id_4oReRJJVlE;
	float target_lat_ahLIi84nTU;
	float target_lon_YqrIpj6DG6;
	float* lat_EUsR6fkEl3;
	float* dists_jbh7EdxpXo;
	int NUM_CORES;
	int NUM_GPUS;

	NUM_CORES = 47;
	NUM_GPUS = 0;
	std::vector<pthread_t> pthreads(0);
	std::vector<Thread*> pool(NUM_CORES);
	setPool(&pool,&pthreads);
	std::vector<ThreadGPU> gpu_pool(NUM_GPUS);
	setGPUPool(&gpu_pool);
	startExecution();
	startGPUExecution();
	neighbor_dist_BOG4iSodlN = Init_List(100000, neighbor_dist_BOG4iSodlN, 5LL * 1LL);
	dists_jbh7EdxpXo = Init_List(dists_jbh7EdxpXo, 42764LL * 1LL);
	lon_eOLMuPEYrA = Init_List(lon_eOLMuPEYrA, 42764LL * 1LL);
	neighbor_id_4oReRJJVlE = Init_List(neighbor_id_4oReRJJVlE, 5LL * 1LL);
	times_UZT91L6oCj = Init_List(times_UZT91L6oCj, 4LL * 1LL);
	lat_EUsR6fkEl3 = Init_List(lat_EUsR6fkEl3, 42764LL * 1LL);
	ii_m0W5Go1hvm_QMDA3CFZtp = 0;
	target_lon_YqrIpj6DG6 = 90;
	target_lat_ahLIi84nTU = 30;
	
if ((ii_m0W5Go1hvm_QMDA3CFZtp == 0)) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 1) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 2) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[0] = get_time();
auto f_1_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 0; INDEX_nKE0ztkvLO < 0 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(0)->addWork(f_1_nKE0ztkvLO);
	auto f_2_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 1859; INDEX_nKE0ztkvLO < 1859 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(1)->addWork(f_2_nKE0ztkvLO);
	auto f_3_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 3718; INDEX_nKE0ztkvLO < 3718 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(2)->addWork(f_3_nKE0ztkvLO);
	auto f_4_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 5577; INDEX_nKE0ztkvLO < 5577 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(3)->addWork(f_4_nKE0ztkvLO);
	auto f_5_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 7436; INDEX_nKE0ztkvLO < 7436 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(4)->addWork(f_5_nKE0ztkvLO);
	auto f_6_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 9295; INDEX_nKE0ztkvLO < 9295 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(5)->addWork(f_6_nKE0ztkvLO);
	auto f_7_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 11154; INDEX_nKE0ztkvLO < 11154 + 1859; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(6)->addWork(f_7_nKE0ztkvLO);
	auto f_8_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 13013; INDEX_nKE0ztkvLO < 13013 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(7)->addWork(f_8_nKE0ztkvLO);
	auto f_9_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 14871; INDEX_nKE0ztkvLO < 14871 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(8)->addWork(f_9_nKE0ztkvLO);
	auto f_10_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 16729; INDEX_nKE0ztkvLO < 16729 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(9)->addWork(f_10_nKE0ztkvLO);
	auto f_11_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 18587; INDEX_nKE0ztkvLO < 18587 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(10)->addWork(f_11_nKE0ztkvLO);
	auto f_12_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 20445; INDEX_nKE0ztkvLO < 20445 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(11)->addWork(f_12_nKE0ztkvLO);
	auto f_13_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 22303; INDEX_nKE0ztkvLO < 22303 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(12)->addWork(f_13_nKE0ztkvLO);
	auto f_14_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 24161; INDEX_nKE0ztkvLO < 24161 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(13)->addWork(f_14_nKE0ztkvLO);
	auto f_15_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 26019; INDEX_nKE0ztkvLO < 26019 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(14)->addWork(f_15_nKE0ztkvLO);
	auto f_16_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 27877; INDEX_nKE0ztkvLO < 27877 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(15)->addWork(f_16_nKE0ztkvLO);
	auto f_17_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 29735; INDEX_nKE0ztkvLO < 29735 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(16)->addWork(f_17_nKE0ztkvLO);
	auto f_18_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 31593; INDEX_nKE0ztkvLO < 31593 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(17)->addWork(f_18_nKE0ztkvLO);
	auto f_19_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 33451; INDEX_nKE0ztkvLO < 33451 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(18)->addWork(f_19_nKE0ztkvLO);
	auto f_20_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 35309; INDEX_nKE0ztkvLO < 35309 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(19)->addWork(f_20_nKE0ztkvLO);
	auto f_21_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 37167; INDEX_nKE0ztkvLO < 37167 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(20)->addWork(f_21_nKE0ztkvLO);
	auto f_22_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 39025; INDEX_nKE0ztkvLO < 39025 + 1858; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(21)->addWork(f_22_nKE0ztkvLO);
	auto f_23_nKE0ztkvLO = [&] () {
		for (size_t INDEX_nKE0ztkvLO = 40883; INDEX_nKE0ztkvLO < 40883 + 1881; ++INDEX_nKE0ztkvLO) {
			dists_jbh7EdxpXo[(INDEX_nKE0ztkvLO)] = sqrt((lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_nKE0ztkvLO)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_nKE0ztkvLO)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(22)->addWork(f_23_nKE0ztkvLO);
	ii_m0W5Go1hvm_QMDA3CFZtp++;
	Bit_Mask * mask_ptr_P2mSGEK3d9 = new Bit_Mask(47,true);
	for (size_t i_7um6qO22Fu = 0; i_7um6qO22Fu < 23; ++i_7um6qO22Fu) {
		mask_ptr_P2mSGEK3d9->setBarrier(i_7um6qO22Fu);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_P2mSGEK3d9 (mask_ptr_P2mSGEK3d9);
	self_barrier(boost_mask_ptr_P2mSGEK3d9);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_BOG4iSodlN[(j)] > max_val) {
				max_val = neighbor_dist_BOG4iSodlN[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jbh7EdxpXo[(i)]) {
			neighbor_dist_BOG4iSodlN[(max_id)] = dists_jbh7EdxpXo[(i)];
			neighbor_id_4oReRJJVlE[(max_id)] = i;
		}
	}
	time[0] = get_time() - time[0];
if ((ii_m0W5Go1hvm_QMDA3CFZtp == 0)) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 1) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 2) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[1] = get_time();
auto f_1_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 0; INDEX_zgbP5blpt2 < 0 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(0)->addWork(f_1_zgbP5blpt2);
	auto f_2_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 1859; INDEX_zgbP5blpt2 < 1859 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(1)->addWork(f_2_zgbP5blpt2);
	auto f_3_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 3718; INDEX_zgbP5blpt2 < 3718 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(2)->addWork(f_3_zgbP5blpt2);
	auto f_4_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 5577; INDEX_zgbP5blpt2 < 5577 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(3)->addWork(f_4_zgbP5blpt2);
	auto f_5_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 7436; INDEX_zgbP5blpt2 < 7436 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(4)->addWork(f_5_zgbP5blpt2);
	auto f_6_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 9295; INDEX_zgbP5blpt2 < 9295 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(5)->addWork(f_6_zgbP5blpt2);
	auto f_7_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 11154; INDEX_zgbP5blpt2 < 11154 + 1859; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(6)->addWork(f_7_zgbP5blpt2);
	auto f_8_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 13013; INDEX_zgbP5blpt2 < 13013 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(7)->addWork(f_8_zgbP5blpt2);
	auto f_9_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 14871; INDEX_zgbP5blpt2 < 14871 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(8)->addWork(f_9_zgbP5blpt2);
	auto f_10_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 16729; INDEX_zgbP5blpt2 < 16729 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(9)->addWork(f_10_zgbP5blpt2);
	auto f_11_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 18587; INDEX_zgbP5blpt2 < 18587 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(10)->addWork(f_11_zgbP5blpt2);
	auto f_12_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 20445; INDEX_zgbP5blpt2 < 20445 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(11)->addWork(f_12_zgbP5blpt2);
	auto f_13_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 22303; INDEX_zgbP5blpt2 < 22303 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(12)->addWork(f_13_zgbP5blpt2);
	auto f_14_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 24161; INDEX_zgbP5blpt2 < 24161 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(13)->addWork(f_14_zgbP5blpt2);
	auto f_15_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 26019; INDEX_zgbP5blpt2 < 26019 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(14)->addWork(f_15_zgbP5blpt2);
	auto f_16_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 27877; INDEX_zgbP5blpt2 < 27877 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(15)->addWork(f_16_zgbP5blpt2);
	auto f_17_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 29735; INDEX_zgbP5blpt2 < 29735 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(16)->addWork(f_17_zgbP5blpt2);
	auto f_18_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 31593; INDEX_zgbP5blpt2 < 31593 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(17)->addWork(f_18_zgbP5blpt2);
	auto f_19_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 33451; INDEX_zgbP5blpt2 < 33451 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(18)->addWork(f_19_zgbP5blpt2);
	auto f_20_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 35309; INDEX_zgbP5blpt2 < 35309 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(19)->addWork(f_20_zgbP5blpt2);
	auto f_21_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 37167; INDEX_zgbP5blpt2 < 37167 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(20)->addWork(f_21_zgbP5blpt2);
	auto f_22_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 39025; INDEX_zgbP5blpt2 < 39025 + 1858; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(21)->addWork(f_22_zgbP5blpt2);
	auto f_23_zgbP5blpt2 = [&] () {
		for (size_t INDEX_zgbP5blpt2 = 40883; INDEX_zgbP5blpt2 < 40883 + 1881; ++INDEX_zgbP5blpt2) {
			dists_jbh7EdxpXo[(INDEX_zgbP5blpt2)] = sqrt((lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_zgbP5blpt2)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_zgbP5blpt2)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(22)->addWork(f_23_zgbP5blpt2);
	ii_m0W5Go1hvm_QMDA3CFZtp++;
	time[1] = get_time() - time[1];
if ((ii_m0W5Go1hvm_QMDA3CFZtp == 0)) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 1) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 2) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	Bit_Mask * mask_ptr_RW46jv7Mvv = new Bit_Mask(47,true);
	for (size_t i_C52XLA2Muz = 0; i_C52XLA2Muz < 23; ++i_C52XLA2Muz) {
		mask_ptr_RW46jv7Mvv->setBarrier(i_C52XLA2Muz);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_RW46jv7Mvv (mask_ptr_RW46jv7Mvv);
	self_barrier(boost_mask_ptr_RW46jv7Mvv);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_BOG4iSodlN[(j)] > max_val) {
				max_val = neighbor_dist_BOG4iSodlN[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jbh7EdxpXo[(i)]) {
			neighbor_dist_BOG4iSodlN[(max_id)] = dists_jbh7EdxpXo[(i)];
			neighbor_id_4oReRJJVlE[(max_id)] = i;
		}
	}
	time[2] = get_time();
auto f_1_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 0; INDEX_TECA9CGyZA < 0 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(0)->addWork(f_1_TECA9CGyZA);
	auto f_2_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 1859; INDEX_TECA9CGyZA < 1859 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(1)->addWork(f_2_TECA9CGyZA);
	auto f_3_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 3718; INDEX_TECA9CGyZA < 3718 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(2)->addWork(f_3_TECA9CGyZA);
	auto f_4_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 5577; INDEX_TECA9CGyZA < 5577 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(3)->addWork(f_4_TECA9CGyZA);
	auto f_5_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 7436; INDEX_TECA9CGyZA < 7436 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(4)->addWork(f_5_TECA9CGyZA);
	auto f_6_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 9295; INDEX_TECA9CGyZA < 9295 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(5)->addWork(f_6_TECA9CGyZA);
	auto f_7_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 11154; INDEX_TECA9CGyZA < 11154 + 1859; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(6)->addWork(f_7_TECA9CGyZA);
	auto f_8_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 13013; INDEX_TECA9CGyZA < 13013 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(7)->addWork(f_8_TECA9CGyZA);
	auto f_9_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 14871; INDEX_TECA9CGyZA < 14871 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(8)->addWork(f_9_TECA9CGyZA);
	auto f_10_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 16729; INDEX_TECA9CGyZA < 16729 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(9)->addWork(f_10_TECA9CGyZA);
	auto f_11_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 18587; INDEX_TECA9CGyZA < 18587 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(10)->addWork(f_11_TECA9CGyZA);
	auto f_12_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 20445; INDEX_TECA9CGyZA < 20445 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(11)->addWork(f_12_TECA9CGyZA);
	auto f_13_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 22303; INDEX_TECA9CGyZA < 22303 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(12)->addWork(f_13_TECA9CGyZA);
	auto f_14_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 24161; INDEX_TECA9CGyZA < 24161 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(13)->addWork(f_14_TECA9CGyZA);
	auto f_15_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 26019; INDEX_TECA9CGyZA < 26019 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(14)->addWork(f_15_TECA9CGyZA);
	auto f_16_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 27877; INDEX_TECA9CGyZA < 27877 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(15)->addWork(f_16_TECA9CGyZA);
	auto f_17_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 29735; INDEX_TECA9CGyZA < 29735 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(16)->addWork(f_17_TECA9CGyZA);
	auto f_18_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 31593; INDEX_TECA9CGyZA < 31593 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(17)->addWork(f_18_TECA9CGyZA);
	auto f_19_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 33451; INDEX_TECA9CGyZA < 33451 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(18)->addWork(f_19_TECA9CGyZA);
	auto f_20_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 35309; INDEX_TECA9CGyZA < 35309 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(19)->addWork(f_20_TECA9CGyZA);
	auto f_21_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 37167; INDEX_TECA9CGyZA < 37167 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(20)->addWork(f_21_TECA9CGyZA);
	auto f_22_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 39025; INDEX_TECA9CGyZA < 39025 + 1858; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(21)->addWork(f_22_TECA9CGyZA);
	auto f_23_TECA9CGyZA = [&] () {
		for (size_t INDEX_TECA9CGyZA = 40883; INDEX_TECA9CGyZA < 40883 + 1881; ++INDEX_TECA9CGyZA) {
			dists_jbh7EdxpXo[(INDEX_TECA9CGyZA)] = sqrt((lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_TECA9CGyZA)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_TECA9CGyZA)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(22)->addWork(f_23_TECA9CGyZA);
	ii_m0W5Go1hvm_QMDA3CFZtp++;
	Bit_Mask * mask_ptr_cvxaCYviEN = new Bit_Mask(47,true);
	for (size_t i_UDpMqFRILR = 0; i_UDpMqFRILR < 23; ++i_UDpMqFRILR) {
		mask_ptr_cvxaCYviEN->setBarrier(i_UDpMqFRILR);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_cvxaCYviEN (mask_ptr_cvxaCYviEN);
	self_barrier(boost_mask_ptr_cvxaCYviEN);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_BOG4iSodlN[(j)] > max_val) {
				max_val = neighbor_dist_BOG4iSodlN[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jbh7EdxpXo[(i)]) {
			neighbor_dist_BOG4iSodlN[(max_id)] = dists_jbh7EdxpXo[(i)];
			neighbor_id_4oReRJJVlE[(max_id)] = i;
		}
	}
	time[2] = get_time() - time[2];
if ((ii_m0W5Go1hvm_QMDA3CFZtp == 0)) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_0.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 1) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_1.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else 	if (ii_m0W5Go1hvm_QMDA3CFZtp == 2) {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_2.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	} else {
		Set_Partial_Array(lon_eOLMuPEYrA, &f_read("longitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
		Set_Partial_Array(lat_EUsR6fkEl3, &f_read("latitudes_3.txt", 1LL * 42764LL)[0], 1LL * 42764LL);
	}
	time[3] = get_time();
auto f_1_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 0; INDEX_M3YVaAICqK < 0 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(0)->addWork(f_1_M3YVaAICqK);
	auto f_2_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 1859; INDEX_M3YVaAICqK < 1859 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(1)->addWork(f_2_M3YVaAICqK);
	auto f_3_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 3718; INDEX_M3YVaAICqK < 3718 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(2)->addWork(f_3_M3YVaAICqK);
	auto f_4_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 5577; INDEX_M3YVaAICqK < 5577 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(3)->addWork(f_4_M3YVaAICqK);
	auto f_5_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 7436; INDEX_M3YVaAICqK < 7436 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(4)->addWork(f_5_M3YVaAICqK);
	auto f_6_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 9295; INDEX_M3YVaAICqK < 9295 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(5)->addWork(f_6_M3YVaAICqK);
	auto f_7_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 11154; INDEX_M3YVaAICqK < 11154 + 1859; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(6)->addWork(f_7_M3YVaAICqK);
	auto f_8_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 13013; INDEX_M3YVaAICqK < 13013 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(7)->addWork(f_8_M3YVaAICqK);
	auto f_9_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 14871; INDEX_M3YVaAICqK < 14871 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(8)->addWork(f_9_M3YVaAICqK);
	auto f_10_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 16729; INDEX_M3YVaAICqK < 16729 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(9)->addWork(f_10_M3YVaAICqK);
	auto f_11_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 18587; INDEX_M3YVaAICqK < 18587 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(10)->addWork(f_11_M3YVaAICqK);
	auto f_12_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 20445; INDEX_M3YVaAICqK < 20445 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(11)->addWork(f_12_M3YVaAICqK);
	auto f_13_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 22303; INDEX_M3YVaAICqK < 22303 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(12)->addWork(f_13_M3YVaAICqK);
	auto f_14_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 24161; INDEX_M3YVaAICqK < 24161 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(13)->addWork(f_14_M3YVaAICqK);
	auto f_15_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 26019; INDEX_M3YVaAICqK < 26019 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(14)->addWork(f_15_M3YVaAICqK);
	auto f_16_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 27877; INDEX_M3YVaAICqK < 27877 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(15)->addWork(f_16_M3YVaAICqK);
	auto f_17_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 29735; INDEX_M3YVaAICqK < 29735 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(16)->addWork(f_17_M3YVaAICqK);
	auto f_18_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 31593; INDEX_M3YVaAICqK < 31593 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(17)->addWork(f_18_M3YVaAICqK);
	auto f_19_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 33451; INDEX_M3YVaAICqK < 33451 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(18)->addWork(f_19_M3YVaAICqK);
	auto f_20_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 35309; INDEX_M3YVaAICqK < 35309 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(19)->addWork(f_20_M3YVaAICqK);
	auto f_21_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 37167; INDEX_M3YVaAICqK < 37167 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(20)->addWork(f_21_M3YVaAICqK);
	auto f_22_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 39025; INDEX_M3YVaAICqK < 39025 + 1858; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(21)->addWork(f_22_M3YVaAICqK);
	auto f_23_M3YVaAICqK = [&] () {
		for (size_t INDEX_M3YVaAICqK = 40883; INDEX_M3YVaAICqK < 40883 + 1881; ++INDEX_M3YVaAICqK) {
			dists_jbh7EdxpXo[(INDEX_M3YVaAICqK)] = sqrt((lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) * (lon_eOLMuPEYrA[(INDEX_M3YVaAICqK)] - target_lon_YqrIpj6DG6) + (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU) * (lat_EUsR6fkEl3[(INDEX_M3YVaAICqK)] - target_lat_ahLIi84nTU));
		}
	};
	getPool()->at(22)->addWork(f_23_M3YVaAICqK);
	ii_m0W5Go1hvm_QMDA3CFZtp++;
	Bit_Mask * mask_ptr_Nc37DTToee = new Bit_Mask(47,true);
	for (size_t i_S2jnymhDVV = 0; i_S2jnymhDVV < 23; ++i_S2jnymhDVV) {
		mask_ptr_Nc37DTToee->setBarrier(i_S2jnymhDVV);
	}
	boost::shared_ptr<Bit_Mask>boost_mask_ptr_Nc37DTToee (mask_ptr_Nc37DTToee);
	self_barrier(boost_mask_ptr_Nc37DTToee);
	for ( int32_t i = 0; i < 42764; i++ ) {
		float max_val;
		int32_t max_id;
		max_id = 0;
		max_val = 0 - 1;
		for ( int32_t j = 0; j < 5; j++ ) {
			if (neighbor_dist_BOG4iSodlN[(j)] > max_val) {
				max_val = neighbor_dist_BOG4iSodlN[(j)];
				max_id = j;
			}
		}
		if (max_val > dists_jbh7EdxpXo[(i)]) {
			neighbor_dist_BOG4iSodlN[(max_id)] = dists_jbh7EdxpXo[(i)];
			neighbor_id_4oReRJJVlE[(max_id)] = i;
		}
	}
	time[3] = get_time() - time[3];
long long time_sum = 0;
for(int i = 0; i<4;i++)
{time_sum += time[i];}
print("Time: ", time_sum);
array_write("dists.txt", neighbor_dist_BOG4iSodlN, 1LL * 5);
	array_write("canes.txt", neighbor_id_4oReRJJVlE, 1LL * 5);
	finishExecution();
	finishGPUExecution();
	std::free(lon_eOLMuPEYrA);
	std::free(neighbor_dist_BOG4iSodlN);
	std::free(times_UZT91L6oCj);
	std::free(neighbor_id_4oReRJJVlE);
	std::free(lat_EUsR6fkEl3);
	std::free(dists_jbh7EdxpXo);
	return 0;


}

