
/*********************************************************************/
/*        This is a generated C++ Header file.                       */
/*        Generated by PatternDSL.                                   */
/*        Contains the function declarations for the source file     */
/*********************************************************************/

#ifndef myocyte_g_1_HXX
#define myocyte_g_1_HXX

uint randomizer(int n = 42) {
    srand(n);
    return rand();
}

    float* embedded_fehlberg_7_8(float timeinst, float h, float* initvalu, float* parameter);
    float* ecc(float timeinst, float* initvalu, int32_t initvalu_offset, float* parameter, int32_t parameter_offset);
    float* fin(float* initvalu, int32_t initvalu_offset_ecc, int32_t initvalu_offset_Dyad, int32_t initvalu_offset_SL, int32_t initvalu_offset_Cyt, float* parameter, float* finavalu, float JCaDyad, float JCaSL, float JCaCyt);
    float* single_iteration(float* y, float* params);
    float* cam(float timeinst, float* initvalu, int32_t initvalu_offset, float* parameter, int32_t parameter_offset, float Ca);
    float* master(float timeinst, float* initvalu, float* parameter);


#endif